//Exported methods
export const abilityHero = [
  {
    title: "Path of the Archer",
    age: "1",
    imgSrc: "/assets/pictures/ability_jeanne/ability-path-of-the-archer-1.png",
    civ: ["JDA"],
    class: "tech",
  },
  {
    title: "Path of the Warrior",
    age: "1",
    imgSrc: "/assets/pictures/ability_jeanne/ability-path-of-the-warrior-1.png",
    civ: ["JDA"],
    class: "tech",
  },
  {
    title: "Champion Companions",
    age: "1",
    imgSrc: "/assets/pictures/ability_jeanne/ability-champion-companions-1.png",
    civ: ["JDA"],
    class: "tech",
  },
  {
    title: "Rider Companions",
    age: "1",
    imgSrc: "/assets/pictures/ability_jeanne/ability-rider-companions-1.png",
    civ: ["JDA"],
    class: "tech",
  },
  {
    title: "Field Commander",
    age: "1",
    imgSrc: "/assets/pictures/ability_jeanne/ability-field-commander-1.png",
    civ: ["JDA"],
    class: "tech",
  },
  {
    title: "Gunpowder Monarch",
    age: "1",
    imgSrc: "/assets/pictures/ability_jeanne/ability-gunpowder-monarch-1.png",
    civ: ["JDA"],
    class: "tech",
  },
  {
    title: "Divine Restoration",
    age: "1",
    imgSrc: "/assets/pictures/ability_jeanne/ability-divine-restoration-1.png",
    civ: ["JDA"],
    class: "ability",
  },
  {
    title: "Divine Arrow",
    age: "1",
    imgSrc: "/assets/pictures/ability_jeanne/ability-divine-arrow-1.png",
    civ: ["JDA"],
    class: "ability",
  },
  {
    title: "Consecrate",
    age: "1",
    imgSrc: "/assets/pictures/ability_jeanne/ability-consecrate-1.png",
    civ: ["JDA"],
    class: "ability",
  },
  {
    title: "Holy Wrath",
    age: "1",
    imgSrc: "/assets/pictures/ability_jeanne/ability-holy-wrath-1.png",
    civ: ["JDA"],
    class: "ability",
  },
  {
    title: "To arms, men!",
    age: "1",
    imgSrc: "/assets/pictures/ability_jeanne/ability-to-arms-men-1.png",
    civ: ["JDA"],
    class: "ability",
  },
  {
    title: "Riders, Ready!",
    age: "1",
    imgSrc: "/assets/pictures/ability_jeanne/ability-riders-ready-1.png",
    civ: ["JDA"],
    class: "ability",
  },
  {
    title: "Strength of Heaven",
    age: "1",
    imgSrc: "/assets/pictures/ability_jeanne/ability-strength-of-heaven-1.png",
    civ: ["JDA"],
    class: "ability",
  },
  {
    title: "Valorous Inspiration",
    age: "1",
    imgSrc: "/assets/pictures/ability_jeanne/ability-valorous-inspiration-1.png",
    civ: ["JDA"],
    class: "ability",
  },
  {
    title: "Supervise",
    age: "1",
    imgSrc: "/assets/pictures/ability_chinese/supervise.png",
    civ: ["CHI"],
    class: "ability",
  },
  {
    title: "Collect Tax",
    age: "1",
    imgSrc: "/assets/pictures/ability_chinese/collect_tax.png",
    civ: ["CHI"],
    class: "ability",
  },
];
