//Composables
import { civs } from "@/composables/builds/icons/civs.js";

//Exported methods
export const buildingMilitary = [
  {
    title: "Barracks",
    age: "1",
    imgSrc: "/assets/pictures/building_military/barracks.png",
    civ: civs,
    class: "military",
    shorthand: ["rax", "qs"],
  },
  {
    title: "Military School",
    age: "1",
    imgSrc: "/assets/pictures/building_ottomans/military-school-1.png",
    civ: ["OTT"],
    class: "military",
  },
  {
    title: "Archery Range",
    age: "2",
    imgSrc: "/assets/pictures/building_military/archery-range.png",
    civ: civs,
    class: "military",
    shorthand: ["archeryrange", "wa"],
  },
  {
    title: "Stable",
    age: "2",
    imgSrc: "/assets/pictures/building_military/stable.png",
    civ: civs,
    class: "military",
    shorthand: ["stable", "ws"],
  },
  {
    title: "Mercenary House",
    age: "2",
    imgSrc: "/assets/pictures/building_byzantines/mercenary-house-2.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Siege Workshop",
    age: "3",
    imgSrc: "/assets/pictures/building_military/siege-workshop.png",
    civ: civs,
    class: "military",
    shorthand: ["workshop", "ea"],
  },
  {
    title: "Dock",
    age: "1",
    imgSrc: "/assets/pictures/building_military/dock.png",
    civ: civs,
    class: "military",
    shorthand: ["dock", "qd"],
  },
  {
    title: "Keep",
    age: "3",
    imgSrc: "/assets/pictures/building_defensive/keep.png",
    civ: civs.exceptMany(["MON", "JAP"]),
    class: "default",
    shorthand: ["keep", "qz", "qy"],
  },
  {
    title: "Castle",
    age: "4",
    imgSrc: "/assets/pictures/building_japanese/castle-4.png",
    civ: ["JAP"],
    class: "default",
  },
  {
    title: "Aqueduct",
    age: "2",
    imgSrc: "/assets/pictures/building_byzantines/aqueduct-1.png",
    civ: ["BYZ"],
    class: "default",
  },
  {
    title: "Outpost",
    age: "1",
    imgSrc: "/assets/pictures/building_defensive/outpost.png",
    civ: civs.exceptMany(["RUS", "MAL"]),
    class: "default",
    shorthand: ["outpost", "qy", "qz"],
  },
  {
    title: "Toll Outpost",
    age: "1",
    imgSrc: "/assets/pictures/building_malians/toll-outpost-1.png",
    civ: ["MAL"],
    class: "default",
  },
  {
    title: "Palisade Gate",
    age: "1",
    imgSrc: "/assets/pictures/building_defensive/palisade-gate.png",
    civ: civs.exceptMany(["RUS", "MON"]),
    class: "default",
    shorthand: ["palgate", "qx"],
  },
  {
    title: "Palisade Wall",
    age: "1",
    imgSrc: "/assets/pictures/building_defensive/palisade-wall.png",
    civ: civs.exceptMany(["RUS", "MON"]),
    class: "default",
    shorthand: ["palwall", "qc"],
  },
  {
    title: "Wooden Fortress",
    age: "1",
    imgSrc: "/assets/pictures/building_rus/wooden-fortress.png",
    civ: ["RUS"],
    class: "default",
  },
  {
    title: "Fortified Palisade Gate",
    age: "1",
    imgSrc: "/assets/pictures/building_rus/fortified-palisade-gate.png",
    civ: ["RUS"],
    class: "default",
  },
  {
    title: "Fortified Palisade Wall",
    age: "1",
    imgSrc: "/assets/pictures/building_rus/fortified-palisade-wall.png",
    civ: ["RUS"],
    class: "default",
  },
  {
    title: "Stone Wall",
    age: "3",
    imgSrc: "/assets/pictures/building_defensive/stone-wall.png",
    civ: civs.exceptMany(["MON"]),
    class: "default",
    shorthand: ["stonewall", "qx"],
  },
  {
    title: "Stone Wall Gate",
    age: "3",
    imgSrc: "/assets/pictures/building_defensive/stone-wall-gate.png",
    civ: civs.exceptMany(["MON"]),
    class: "default",
    shorthand: ["stonegate", "qc"],
  },
  {
    title: "Stone Wall Tower",
    age: "3",
    imgSrc: "/assets/pictures/building_defensive/stone-wall-tower.png",
    civ: civs.exceptMany(["MON"]),
    class: "default",
    shorthand: ["stonetower", "qz", "qy"],
  },
];
