//Composables
import { civs } from "@/composables/builds/icons/civs.js";

export const general = [
  {
    title: "Dark Age",
    age: "1",
    imgSrc: "/assets/pictures/age/age_1.png",
    civ: civs,
    class: "none",
    shorthand: "age1",
  },
  {
    title: "Feudal Age",
    age: "2",
    imgSrc: "/assets/pictures/age/age_2.png",
    civ: civs,
    class: "none",
    shorthand: "age2",
  },
  {
    title: "Castle Age",
    age: "3",
    imgSrc: "/assets/pictures/age/age_3.png",
    civ: civs,
    class: "none",
    shorthand: "age3",
  },
  {
    title: "Imperial Age",
    age: "4",
    imgSrc: "/assets/pictures/age/age_4.png",
    civ: civs,
    class: "none",
    shorthand: "age4",
  },
  {
    title: "Golden Age Tier 1",
    age: "1",
    imgSrc: "/assets/pictures/age/goldenagetier1.png",
    civ: ["ABB", "AYY"],
    class: "none",
  },
  {
    title: "Golden Age Tier 2",
    age: "4",
    imgSrc: "/assets/pictures/age/goldenagetier2.png",
    civ: ["ABB", "AYY"],
    class: "none",
  },
  {
    title: "Golden Age Tier 3",
    age: "1",
    imgSrc: "/assets/pictures/age/goldenagetier3.png",
    civ: ["ABB", "AYY"],
    class: "none",
  },
  {
    title: "Golden Age Tier 4",
    age: "1",
    imgSrc: "/assets/pictures/age/goldenagetier4.png",
    civ: ["AYY"],
    class: "none",
  },
  {
    title: "Golden Age Tier 5",
    age: "1",
    imgSrc: "/assets/pictures/age/goldenagetier5.png",
    civ: ["AYY"],
    class: "none",
  },
  {
    title: "Vizier Point",
    age: "1",
    imgSrc: "/assets/pictures/age/vizier_point.png",
    civ: ["OTT"],
    class: "none",
  },
  {
    title: "Build or Repair",
    age: "1",
    imgSrc: "/assets/pictures/abilities/repair.png",
    civ: civs,
    class: "none",
    shorthand: "build",
  },
  {
    title: "Attack",
    age: "1",
    imgSrc: "/assets/pictures/abilities/attack-move.png",
    civ: civs,
    class: "none",
  },
  {
    title: "Abbasid Dynasty",
    age: "1",
    imgSrc: "/assets/pictures/civilization_flag/abb.png",
    civ: civs,
    class: "none",
    shorthand: "abb",
  },
  {
    title: "Ayyubids",
    age: "1",
    imgSrc: "/assets/pictures/civilization_flag/ayy.png",
    civ: civs,
    class: "none",
    shorthand: "ayy",
  },
  {
    title: "Byzantines",
    age: "1",
    imgSrc: "/assets/pictures/civilization_flag/byz.png",
    civ: civs,
    class: "none",
    shorthand: "byz",
  },
  {
    title: "China",
    age: "1",
    imgSrc: "/assets/pictures/civilization_flag/chi.png",
    civ: civs,
    class: "none",
    shorthand: "chi",
  },
  {
    title: "Delhi Sultanate",
    age: "1",
    imgSrc: "/assets/pictures/civilization_flag/del.png",
    civ: civs,
    class: "none",
    shorthand: "del",
  },
  {
    title: "English",
    age: "1",
    imgSrc: "/assets/pictures/civilization_flag/eng.png",
    civ: civs,
    class: "none",
    shorthand: "eng",
  },
  {
    title: "French",
    age: "1",
    imgSrc: "/assets/pictures/civilization_flag/fre.png",
    civ: civs,
    class: "none",
    shorthand: "fre",
  },
  {
    title: "Holy Roman Empire",
    age: "1",
    imgSrc: "/assets/pictures/civilization_flag/hre.png",
    civ: civs,
    class: "none",
    shorthand: "hre",
  },
  {
    title: "Japanese",
    age: "1",
    imgSrc: "/assets/pictures/civilization_flag/jap.png",
    civ: civs,
    class: "none",
    shorthand: "jap",
  },
  {
    title: "Jeanne d'Arc",
    age: "1",
    imgSrc: "/assets/pictures/civilization_flag/jda.png",
    civ: civs,
    class: "none",
    shorthand: "jda",
  },
  {
    title: "Malians",
    age: "1",
    imgSrc: "/assets/pictures/civilization_flag/mal.png",
    civ: civs,
    class: "none",
    shorthand: "mal",
  },
  {
    title: "Mongols",
    age: "1",
    imgSrc: "/assets/pictures/civilization_flag/mon.png",
    civ: civs,
    class: "none",
    shorthand: "mon",
  },
  {
    title: "Order of the Dragon",
    age: "1",
    imgSrc: "/assets/pictures/civilization_flag/dra.png",
    civ: civs,
    class: "none",
    shorthand: "dra",
  },
  {
    title: "Ottomans",
    age: "1",
    imgSrc: "/assets/pictures/civilization_flag/ott.png",
    civ: civs,
    class: "none",
    shorthand: "ott",
  },
  {
    title: "Rus",
    age: "1",
    imgSrc: "/assets/pictures/civilization_flag/rus.png",
    civ: civs,
    class: "none",
    shorthand: "rus",
  },
  {
    title: "Zhu Xi's Legacy",
    age: "1",
    imgSrc: "/assets/pictures/civilization_flag/zxl.png",
    civ: civs,
    class: "none",
    shorthand: "zxl",
  },
];
