//Exported methods
export const landmarks = [
  {
    title: "Abbey of Kings",
    age: "1",
    imgSrc: "/assets/pictures/landmark_english/abbey-of-kings.png",
    civ: ["ENG"],
    class: "landmark",
  },
  {
    title: "Council Hall",
    age: "1",
    imgSrc: "/assets/pictures/landmark_english/council-hall.png",
    civ: ["ENG"],
    class: "landmark",
  },
  {
    title: "King's Palace",
    age: "2",
    imgSrc: "/assets/pictures/landmark_english/kings-palace.png",
    civ: ["ENG"],
    class: "landmark",
  },
  {
    title: "The White Tower",
    age: "2",
    imgSrc: "/assets/pictures/landmark_english/the-white-tower.png",
    civ: ["ENG"],
    class: "landmark",
  },
  {
    title: "Wynguard Palace",
    age: "3",
    imgSrc: "/assets/pictures/landmark_english/wynguard-palace.png",
    civ: ["ENG"],
    class: "landmark",
  },
  {
    title: "Berkshire Palace",
    age: "3",
    imgSrc: "/assets/pictures/landmark_english/berkshire-palace.png",
    civ: ["ENG"],
    class: "landmark",
  },
  {
    title: "Cathedral of St. Thomas",
    age: "4",
    imgSrc: "/assets/pictures/landmark_english/cathedral-of-st-thomas.png",
    civ: ["ENG"],
    class: "landmark",
  },
  {
    title: "Chamber of Commerce",
    age: "1",
    imgSrc: "/assets/pictures/landmark_french/chamber-of-commerce.png",
    civ: ["FRE", "JDA"],
    class: "landmark",
  },
  {
    title: "School of Cavalry",
    age: "1",
    imgSrc: "/assets/pictures/landmark_french/school-of-cavalry.png",
    civ: ["FRE", "JDA"],
    class: "landmark",
  },
  {
    title: "Guild Hall",
    age: "2",
    imgSrc: "/assets/pictures/landmark_french/guild-hall.png",
    civ: ["FRE", "JDA"],
    class: "landmark",
  },
  {
    title: "Royal Institute",
    age: "2",
    imgSrc: "/assets/pictures/landmark_french/royal-institute.png",
    civ: ["FRE", "JDA"],
    class: "landmark",
  },
  {
    title: "College of Artillery",
    age: "3",
    imgSrc: "/assets/pictures/landmark_french/college-of-artillery.png",
    civ: ["FRE", "JDA"],
    class: "landmark",
  },
  {
    title: "Red Palace",
    age: "3",
    imgSrc: "/assets/pictures/landmark_french/red-palace.png",
    civ: ["FRE", "JDA"],
    class: "landmark",
  },
  {
    title: "Notre Dame",
    age: "4",
    imgSrc: "/assets/pictures/landmark_french/notre-dame.png",
    civ: ["FRE", "JDA"],
    class: "landmark",
  },
  {
    title: "Aachen Chapel",
    age: "1",
    imgSrc: "/assets/pictures/landmark_hre/aachen-chapel.png",
    civ: ["HRE", "DRA"],
    class: "landmark",
  },
  {
    title: "Meinwerk Palace",
    age: "1",
    imgSrc: "/assets/pictures/landmark_hre/meinwerk-palace.png",
    civ: ["HRE", "DRA"],
    class: "landmark",
  },
  {
    title: "Burgrave Palace",
    age: "2",
    imgSrc: "/assets/pictures/landmark_hre/burgrave-palace.png",
    civ: ["HRE", "DRA"],
    class: "landmark",
  },
  {
    title: "Regnitz Cathedral",
    age: "2",
    imgSrc: "/assets/pictures/landmark_hre/regnitz-cathedral.png",
    civ: ["HRE", "DRA"],
    class: "landmark",
  },
  {
    title: "Elzbach Palace",
    age: "3",
    imgSrc: "/assets/pictures/landmark_hre/elzbach-palace.png",
    civ: ["HRE", "DRA"],
    class: "landmark",
  },
  {
    title: "Palace of Swabia",
    age: "3",
    imgSrc: "/assets/pictures/landmark_hre/palace-of-swabia.png",
    civ: ["HRE", "DRA"],
    class: "landmark",
  },
  {
    title: "Great Palace of Flensburg",
    age: "4",
    imgSrc: "/assets/pictures/landmark_hre/great-palace-of-flensburg.png",
    civ: ["HRE", "DRA"],
    class: "landmark",
  },
  {
    title: "Saharan Trade Network",
    age: "1",
    imgSrc: "/assets/pictures/landmark_malians/saharan-trade-network-1.png",
    civ: ["MAL"],
    class: "landmark",
  },
  {
    title: "Mansa Quarry",
    age: "1",
    imgSrc: "/assets/pictures/landmark_malians/mansa-quarry-2.png",
    civ: ["MAL"],
    class: "landmark",
  },
  {
    title: "Grand Fulani Corral",
    age: "2",
    imgSrc: "/assets/pictures/landmark_malians/grand-fulani-corral-2.png",
    civ: ["MAL"],
    class: "landmark",
  },
  {
    title: "Farimba Garrison",
    age: "2",
    imgSrc: "/assets/pictures/landmark_malians/farimba-garrison-2.png",
    civ: ["MAL"],
    class: "landmark",
  },
  {
    title: "Fort of the Huntress",
    age: "3",
    imgSrc: "/assets/pictures/landmark_malians/fort-of-the-huntress-3.png",
    civ: ["MAL"],
    class: "landmark",
  },
  {
    title: "Griot Bara",
    age: "3",
    imgSrc: "/assets/pictures/landmark_malians/griot-bara-3.png",
    civ: ["MAL"],
    class: "landmark",
  },
  {
    title: "Great Mosque",
    age: "4",
    imgSrc: "/assets/pictures/landmark_malians/great-mosque-4.png",
    civ: ["MAL"],
    class: "landmark",
  },
  {
    title: "Deer Stones",
    age: "1",
    imgSrc: "/assets/pictures/landmark_mongols/deer-stones.png",
    civ: ["MON"],
    class: "landmark",
  },
  {
    title: "The Silver Tree",
    age: "1",
    imgSrc: "/assets/pictures/landmark_mongols/the-silver-tree.png",
    civ: ["MON"],
    class: "landmark",
  },
  {
    title: "Kurultai",
    age: "2",
    imgSrc: "/assets/pictures/landmark_mongols/kurultai.png",
    civ: ["MON"],
    class: "landmark",
  },
  {
    title: "Steppe Redoubt",
    age: "2",
    imgSrc: "/assets/pictures/landmark_mongols/steppe-redoubt.png",
    civ: ["MON"],
    class: "landmark",
  },
  {
    title: "Khaganate Palace",
    age: "3",
    imgSrc: "/assets/pictures/landmark_mongols/khaganate-palace.png",
    civ: ["MON"],
    class: "landmark",
  },
  {
    title: "The White Stupa",
    age: "3",
    imgSrc: "/assets/pictures/landmark_mongols/the-white-stupa.png",
    civ: ["MON"],
    class: "landmark",
  },
  {
    title: "Monument of the Great Khan",
    age: "4",
    imgSrc:
      "/assets/pictures/landmark_mongols/monument-of-the-great-khan.png",
    civ: ["MON"],
    class: "landmark",
  },
  {
    title: "Twin Minaret Medrese",
    age: "1",
    imgSrc: "/assets/pictures/landmark_ottomans/twin-minaret-medrese-1.png",
    civ: ["OTT"],
    class: "landmark",
  },
  {
    title: "Sultanhani Trade Network",
    age: "1",
    imgSrc:
      "/assets/pictures/landmark_ottomans/sultanhani-trade-network-1.png",
    civ: ["OTT"],
    class: "landmark",
  },
  {
    title: "Istanbul Imperial Palace",
    age: "2",
    imgSrc:
      "/assets/pictures/landmark_ottomans/istanbul-imperial-palace-2.png",
    civ: ["OTT"],
    class: "landmark",
  },
  {
    title: "Mehmed Imperial Armory",
    age: "2",
    imgSrc: "/assets/pictures/landmark_ottomans/mehmed-imperial-armory-2.png",
    civ: ["OTT"],
    class: "landmark",
  },
  {
    title: "Istanbul Observatory",
    age: "3",
    imgSrc: "/assets/pictures/landmark_ottomans/istanbul-observatory-3.png",
    civ: ["OTT"],
    class: "landmark",
  },
  {
    title: "Sea Gate Castle",
    age: "3",
    imgSrc: "/assets/pictures/landmark_ottomans/sea-gate-castle-3.png",
    civ: ["OTT"],
    class: "landmark",
  },
  {
    title: "Azure Mosque",
    age: "4",
    imgSrc: "/assets/pictures/landmark_ottomans/azure-mosque-4.png",
    civ: ["OTT"],
    class: "landmark",
  },
  {
    title: "Kremlin",
    age: "1",
    imgSrc: "/assets/pictures/landmark_rus/kremlin.png",
    civ: ["RUS"],
    class: "landmark",
  },
  {
    title: "The Golden Gate",
    age: "1",
    imgSrc: "/assets/pictures/landmark_rus/the-golden-gate.png",
    civ: ["RUS"],
    class: "landmark",
  },
  {
    title: "Abbey of the Trinity",
    age: "2",
    imgSrc: "/assets/pictures/landmark_rus/abbey-of-the-trinity.png",
    civ: ["RUS"],
    class: "landmark",
  },
  {
    title: "High Trade House",
    age: "2",
    imgSrc: "/assets/pictures/landmark_rus/high-trade-house.png",
    civ: ["RUS"],
    class: "landmark",
  },
  {
    title: "High Armory",
    age: "3",
    imgSrc: "/assets/pictures/landmark_rus/high-armory.png",
    civ: ["RUS"],
    class: "landmark",
  },
  {
    title: "Spasskaya Tower",
    age: "3",
    imgSrc: "/assets/pictures/landmark_rus/spasskaya-tower.png",
    civ: ["RUS"],
    class: "landmark",
  },
  {
    title: "Cathedral of the Tsar",
    age: "4",
    imgSrc: "/assets/pictures/landmark_rus/cathedral-of-the-tsar.png",
    civ: ["RUS"],
    class: "landmark",
  },
  {
    title: "House of Wisdom",
    age: "1",
    imgSrc: "/assets/pictures/landmark_abbasid/house-of-wisdom.png",
    civ: ["ABB", "AYY"],
    class: "landmark",
  },
  {
    title: "Culture Wing",
    age: "1",
    imgSrc: "/assets/pictures/landmark_abbasid/culture-wing.png",
    civ: ["ABB", "AYY"],
    class: "landmark",
  },
  {
    title: "Economic Wing",
    age: "1",
    imgSrc: "/assets/pictures/landmark_abbasid/economic-wing.png",
    civ: ["ABB", "AYY"],
    class: "landmark",
  },
  {
    title: "Military Wing",
    age: "1",
    imgSrc: "/assets/pictures/landmark_abbasid/military-wing.png",
    civ: ["ABB", "AYY"],
    class: "landmark",
  },
  {
    title: "Trade Wing",
    age: "1",
    imgSrc: "/assets/pictures/landmark_abbasid/trade-wing.png",
    civ: ["ABB", "AYY"],
    class: "landmark",
  },
  {
    title: "Meditation Gardens",
    age: "1",
    imgSrc: "/assets/pictures/landmark_zhuxi/meditation-gardens-1.png",
    civ: ["ZXL"],
    class: "landmark",
  },
  {
    title: "Jiangnan Tower",
    age: "1",
    imgSrc: "/assets/pictures/landmark_zhuxi/jiangnan-tower-2.png",
    civ: ["ZXL"],
    class: "landmark",
  },
  {
    title: "Mount Lu Academy",
    age: "2",
    imgSrc: "/assets/pictures/landmark_zhuxi/mount-lu-academy-1.png",
    civ: ["ZXL"],
    class: "landmark",
  },
  {
    title: "Shaolin Monastery",
    age: "2",
    imgSrc: "/assets/pictures/landmark_zhuxi/shaolin-monastery-2.png",
    civ: ["ZXL"],
    class: "landmark",
  },
  {
    title: "Zhu Xi's Library",
    age: "3",
    imgSrc: "/assets/pictures/landmark_zhuxi/zhu-xis-library-3.png",
    civ: ["ZXL"],
    class: "landmark",
  },
  {
    title: "Temple of the Sun",
    age: "3",
    imgSrc: "/assets/pictures/landmark_zhuxi/temple-of-the-sun-3.png",
    civ: ["ZXL"],
    class: "landmark",
  },
  {
    title: "Enclave of the Emperor",
    age: "4",
    imgSrc: "/assets/pictures/landmark_chinese/enclave-of-the-emperor.png",
    civ: ["ZXL"],
    class: "landmark",
  },
  {
    title: "Imperial Academy",
    age: "1",
    imgSrc: "/assets/pictures/landmark_chinese/imperial-academy.png",
    civ: ["CHI"],
    class: "landmark",
  },
  {
    title: "Barbican of the Sun",
    age: "1",
    imgSrc: "/assets/pictures/landmark_chinese/barbican-of-the-sun.png",
    civ: ["CHI"],
    class: "landmark",
  },
  {
    title: "Astronomical Clocktower",
    age: "2",
    imgSrc: "/assets/pictures/landmark_chinese/astronomical-clocktower.png",
    civ: ["CHI"],
    class: "landmark",
  },
  {
    title: "Imperial Palace",
    age: "2",
    imgSrc: "/assets/pictures/landmark_chinese/imperial-palace.png",
    civ: ["CHI"],
    class: "landmark",
  },
  {
    title: "Great Wall Gatehouse",
    age: "3",
    imgSrc: "/assets/pictures/landmark_chinese/great-wall-gatehouse.png",
    civ: ["CHI"],
    class: "landmark",
  },
  {
    title: "Spirit Way",
    age: "3",
    imgSrc: "/assets/pictures/landmark_chinese/spirit-way.png",
    civ: ["CHI"],
    class: "landmark",
  },
  {
    title: "Enclave of the Emperor",
    age: "4",
    imgSrc: "/assets/pictures/landmark_chinese/enclave-of-the-emperor.png",
    civ: ["CHI"],
    class: "landmark",
  },
  {
    title: "Dome of the Faith",
    age: "1",
    imgSrc: "/assets/pictures/landmark_delhi/dome-of-the-faith.png",
    civ: ["DEL"],
    class: "landmark",
  },
  {
    title: "Tower of Victory",
    age: "1",
    imgSrc: "/assets/pictures/landmark_delhi/tower-of-victory.png",
    civ: ["DEL"],
    class: "landmark",
  },
  {
    title: "Compound of the Defender",
    age: "2",
    imgSrc: "/assets/pictures/landmark_delhi/compound-of-the-defender.png",
    civ: ["DEL"],
    class: "landmark",
  },
  {
    title: "House of Learning",
    age: "2",
    imgSrc: "/assets/pictures/landmark_delhi/house-of-learning.png",
    civ: ["DEL"],
    class: "landmark",
  },
  {
    title: "Hisar Academy",
    age: "3",
    imgSrc: "/assets/pictures/landmark_delhi/hisar-academy.png",
    civ: ["DEL"],
    class: "landmark",
  },
  {
    title: "Palace of the Sultan",
    age: "3",
    imgSrc: "/assets/pictures/landmark_delhi/palace-of-the-sultan.png",
    civ: ["DEL"],
    class: "landmark",
  },
  {
    title: "Great Palace of Agra",
    age: "4",
    imgSrc: "/assets/pictures/landmark_delhi/great-palace-of-agra.png",
    civ: ["DEL"],
    class: "landmark",
  },
  {
    title: "Great Mosque of Kairouan",
    age: "4",
    imgSrc: "/assets/pictures/landmark_abbasid/prayer-hall-of-uqba.png",
    civ: ["ABB", "AYY"],
    class: "landmark",
  },
  {
    title: "Grand Winery",
    age: "1",
    imgSrc: "/assets/pictures/landmark_byzantines/grand-winery-1.png",
    civ: ["BYZ"],
    class: "landmark",
  },
  {
    title: "Imperial Hippodrome",
    age: "1",
    imgSrc: "/assets/pictures/landmark_byzantines/imperial-hippodrome-1.png",
    civ: ["BYZ"],
    class: "landmark",
  },
  {
    title: "Cistern of the First Hill",
    age: "2",
    imgSrc: "/assets/pictures/landmark_byzantines/cistern-of-the-first-hill-2.png",
    civ: ["BYZ"],
    class: "landmark",
  },
  {
    title: "Golden Horn Tower",
    age: "2",
    imgSrc: "/assets/pictures/landmark_byzantines/golden-horn-tower-2.png",
    civ: ["BYZ"],
    class: "landmark",
  },
  {
    title: "Palatine School",
    age: "3",
    imgSrc: "/assets/pictures/landmark_byzantines/palatine-school-3.png",
    civ: ["BYZ"],
    class: "landmark",
  },
  {
    title: "Foreign Engineering Company",
    age: "3",
    imgSrc: "/assets/pictures/landmark_byzantines/foreign-engineering-company-3.png",
    civ: ["BYZ"],
    class: "landmark",
  },
  {
    title: "Cathedral of Divine Wisdom",
    age: "4",
    imgSrc: "/assets/pictures/landmark_byzantines/cathedral-of-divine-wisdom-4.png",
    civ: ["BYZ"],
    class: "landmark",
  },
  {
    title: "Koka Township",
    age: "1",
    imgSrc: "/assets/pictures/landmark_japanese/koka-township-1.png",
    civ: ["JAP"],
    class: "landmark",
  },
  {
    title: "Kura Storehouse",
    age: "1",
    imgSrc: "/assets/pictures/landmark_japanese/kura-storehouse-1.png",
    civ: ["JAP"],
    class: "landmark",
  },
  {
    title: "Floating Gate",
    age: "2",
    imgSrc: "/assets/pictures/landmark_japanese/floating-gate-2.png",
    civ: ["JAP"],
    class: "landmark",
  },
  {
    title: "Temple of Equality",
    age: "2",
    imgSrc: "/assets/pictures/landmark_japanese/temple-of-equality-2.png",
    civ: ["JAP"],
    class: "landmark",
  },
  {
    title: "Tanegashima Gunsmith",
    age: "3",
    imgSrc: "/assets/pictures/landmark_japanese/tanegashima-gunsmith-3.png",
    civ: ["JAP"],
    class: "landmark",
  },
  {
    title: "Castle of the Crow",
    age: "3",
    imgSrc: "/assets/pictures/landmark_japanese/castle-of-the-crow-4.png",
    civ: ["JAP"],
    class: "landmark",
  },
  {
    title: "Tokugawa Shrine",
    age: "4",
    imgSrc: "/assets/pictures/landmark_japanese/tokugawa-shrine-4.png",
    civ: ["JAP"],
    class: "landmark",
  },
];
