//Composables
import { civs } from "@/composables/builds/icons/civs.js";

export const resources = [
  {
    title: "Food",
    age: "1",
    imgSrc: "/assets/pictures/resource/resource_food.png",
    civ: civs,
    class: "none",
    shorthand: "food",
  },
  {
    title: "Wood",
    age: "1",
    imgSrc: "/assets/pictures/resource/resource_wood.png",
    civ: civs,
    class: "none",
    shorthand: "wood",
  },
  {
    title: "Gold",
    age: "1",
    imgSrc: "/assets/pictures/resource/resource_gold.png",
    civ: civs,
    class: "none",
    shorthand: "gold",
  },
  {
    title: "Stone",
    age: "1",
    imgSrc: "/assets/pictures/resource/resource_stone.png",
    civ: civs,
    class: "none",
    shorthand: "stone",
  },
  {
    title: "Cattle",
    age: "1",
    imgSrc: "/assets/pictures/resource/cattle.png",
    civ: ["MAL"],
    class: "none",
    shorthand: "cattle",
  },
  {
    title: "Sheep",
    age: "1",
    imgSrc: "/assets/pictures/resource/sheep.png",
    civ: civs,
    class: "none",
    shorthand: "sheep",
  },
  {
    title: "Deer",
    age: "1",
    imgSrc: "/assets/pictures/resource/deer.png",
    civ: civs,
    class: "none",
    shorthand: "deer",
  },
  {
    title: "Berries",
    age: "1",
    imgSrc: "/assets/pictures/resource/berrybush.png",
    civ: civs,
    class: "none",
    shorthand: "berry",
  },
  {
    title: "Boar",
    age: "1",
    imgSrc: "/assets/pictures/resource/boar.png",
    civ: civs,
    class: "none",
    shorthand: "boar",
  },
  {
    title: "Relic",
    age: "1",
    imgSrc: "/assets/pictures/resource/relics.png",
    civ: civs,
    class: "none",
    shorthand: "relic",
  },
  {
    title: "Sacred Site",
    age: "1",
    imgSrc: "/assets/pictures/resource/sacred_sites.png",
    civ: civs,
    class: "none",
    shorthand: "ss",
  },
  {
    title: "Bounty",
    age: "1",
    imgSrc: "/assets/pictures/resource/bounty.png",
    civ: ["RUS"],
    class: "none",
    shorthand: "bounty",
  },
  {
    title: "Rally",
    age: "1",
    imgSrc: "/assets/pictures/resource/rally.png",
    civ: civs,
    class: "none",
    shorthand: "rally",
  },
  {
    title: "Fish",
    age: "1",
    imgSrc: "/assets/pictures/resource/fish.png",
    civ: civs,
    class: "none",
    shorthand: "fish",
  },
  {
    title: "Straggler Tree",
    age: "1",
    imgSrc: "/assets/pictures/resource/gaiatreeprototypetree.png",
    civ: civs,
    class: "none",
    shorthand: "tree",
  },
  ,
  {
    title: "Wolf",
    age: "1",
    imgSrc: "/assets/pictures/resource/wolf.png",
    civ: civs,
    class: "none",
  },
];