//Composables
import { civs } from "@/composables/builds/icons/civs.js";

//Exported methods
export const techMilitary = [
  {
    title: "Bloomery",
    age: "2",
    imgSrc: "/assets/pictures/technology_military/bloomery.png",
    civ: civs.except("JAP"),
    class: "tech",
    shorthand: "melee_dmg1"
  },
  {
    title: "Decarbonization",
    age: "3",
    imgSrc: "/assets/pictures/technology_military/decarbonization.png",
    civ: civs.except("JAP"),
    class: "tech",
    shorthand: "melee_dmg2"
  },
  {
    title: "Damascus Steel",
    age: "4",
    imgSrc: "/assets/pictures/technology_military/damascus-steel.png",
    civ: civs.except("JAP"),
    class: "tech",
    shorthand: "melee_dmg3"
  },
  {
    title: "Tatara",
    age: "1",
    imgSrc: "/assets/pictures/technology_japanese/tatara-1.png",
    civ: ["JAP"],
    class: "tech",
  },
  {
    title: "Hizukuri",
    age: "2",
    imgSrc: "/assets/pictures/technology_japanese/hizukuri-2.png",
    civ: ["JAP"],
    class: "tech",
  },
  {
    title: "Kobuse-gitae",
    age: "3",
    imgSrc: "/assets/pictures/technology_japanese/kobuse-gitae-3.png",
    civ: ["JAP"],
    class: "tech",
  },
  {
    title: "Yaki-ire",
    age: "4",
    imgSrc: "/assets/pictures/technology_japanese/yaki-ire-4.png",
    civ: ["JAP"],
    class: "tech",
  },
  {
    title: "Siege Engineering",
    age: "2",
    imgSrc: "/assets/pictures/technology_military/siege-engineering.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Steeled Arrow",
    age: "2",
    imgSrc: "/assets/pictures/technology_military/steeled-arrow.png",
    civ: civs,
    class: "tech",
    shorthand: "ranged_dmg1"
  },
  {
    title: "Balanced Projectiles",
    age: "3",
    imgSrc: "/assets/pictures/technology_military/balanced-projectiles.png",
    civ: civs,
    class: "tech",
    shorthand: "ranged_dmg2"
  },
  {
    title: "Platecutter Point",
    age: "4",
    imgSrc: "/assets/pictures/technology_military/platecutter-point.png",
    civ: civs,
    class: "tech",
    shorthand: "ranged_dmg3"
  },
  {
    title: "Military Academy",
    age: "4",
    imgSrc: "/assets/pictures/technology_military/military-academy.png",
    civ: civs.exceptMany(["OTT"]),
    class: "tech",
  },
  {
    title: "Fitted Leatherwork",
    age: "2",
    imgSrc: "/assets/pictures/technology_military/fitted-leatherwork.png",
    civ: civs,
    class: "tech",
    shorthand: "melee_def1"
  },
  {
    title: "Insulated Helm",
    age: "3",
    imgSrc: "/assets/pictures/technology_military/insulated-helm.png",
    civ: civs,
    class: "tech",
    shorthand: "melee_def2"
  },
  {
    title: "Master Smiths",
    age: "4",
    imgSrc: "/assets/pictures/technology_military/master-smiths.png",
    civ: civs,
    class: "tech",
    shorthand: "melee_def3"
  },
  {
    title: "Elite Army Tactics",
    age: "4",
    imgSrc: "/assets/pictures/technology_military/elite-army-tactics.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Iron Undermesh",
    age: "2",
    imgSrc: "/assets/pictures/technology_military/iron-undermesh.png",
    civ: civs,
    class: "tech",
    shorthand: "ranged_def1"
  },
  {
    title: "Wedge Rivets",
    age: "3",
    imgSrc: "/assets/pictures/technology_military/wedge-rivets.png",
    civ: civs,
    class: "tech",
    shorthand: "ranged_def2"
  },
  {
    title: "Angled Surfaces",
    age: "4",
    imgSrc: "/assets/pictures/technology_military/angled-surfaces.png",
    civ: civs,
    class: "tech",
    shorthand: "ranged_def3"
  },
  {
    title: "Incendiary Arrows",
    age: "4",
    imgSrc: "/assets/pictures/technology_military/incendiary-arrows.png",
    civ: civs.exceptMany(["MAL"]),
    class: "tech",
  },
  {
    title: "Biology",
    age: "4",
    imgSrc: "/assets/pictures/technology_military/biology.png",
    civ: civs.exceptMany(["OTT"]),
    class: "tech",
  },
  {
    title: "Chemistry",
    age: "4",
    imgSrc: "/assets/pictures/technology_military/chemistry.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "War Horses",
    age: "4",
    imgSrc: "/assets/pictures/technology_dragon/war-horses-4.png",
    civ: ["DRA"],
    class: "tech",
  },
  {
    title: "Geometry",
    age: "4",
    imgSrc: "/assets/pictures/technology_military/geometry.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Greased Axles",
    age: "2",
    imgSrc: "/assets/pictures/technology_military/greased-axles.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Roller Shutter Triggers",
    age: "4",
    imgSrc: "/assets/pictures/technology_units/roller-shutter-triggers.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Spyglass",
    age: "4",
    imgSrc: "/assets/pictures/technology_units/spyglass-4.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Do-maru Armor",
    age: "4",
    imgSrc: "/assets/pictures/technology_japanese/do-maru-armor-4.png",
    civ: ["JAP"],
    class: "tech",
  },
  {
    title: "Nagae Yari",
    age: "4",
    imgSrc: "/assets/pictures/technology_japanese/nagae-yari-4.png",
    civ: ["JAP"],
    class: "tech",
  },
  {
    title: "Golden Cuirass",
    age: "2",
    imgSrc: "/assets/pictures/technology_dragon/golden-cuirass-2.png",
    civ: ["DRA"],
    class: "tech",
  },
  {
    title: "Dragon Fire",
    age: "3",
    imgSrc: "/assets/pictures/technology_dragon/dragon-fire-2.png",
    civ: ["DRA"],
    class: "tech",
  },
  {
    title: "Dragon Scale Leather",
    age: "3",
    imgSrc: "/assets/pictures/technology_dragon/dragon-scale-leather-3.png",
    civ: ["DRA"],
    class: "tech",
  },
  {
    title: "Zornhau",
    age: "3",
    imgSrc: "/assets/pictures/technology_dragon/zornhau-3.png",
    civ: ["DRA"],
    class: "tech",
  },
  {
    title: "Bodkin Bolts",
    age: "4",
    imgSrc: "/assets/pictures/technology_dragon/bodkin-bolts-4.png",
    civ: ["DRA"],
    class: "tech",
  },
  {
    title: "Lightweight Beams",
    age: "4",
    imgSrc: "/assets/pictures/technology_units/lightweight-beams-4.png",
    civ: civs.exceptMany("BYZ"),
    class: "tech",
  },
  {
    title: "Adjustable Crossbars",
    age: "4",
    imgSrc: "/assets/pictures/technology_units/adjustable-crossbars.png",
    civ: civs.exceptMany(["CHI", "ZXL"]),
    class: "tech",
  },
  {
    title: "Siege Works",
    age: "4",
    imgSrc: "/assets/pictures/technology_military/siege-works.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Arrowslits",
    age: "2",
    imgSrc: "/assets/pictures/technology_defensive/arrow-slits.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Springald Emplacement",
    age: "3",
    imgSrc: "/assets/pictures/technology_defensive/springald-emplacement.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Cannon Emplacement",
    age: "3",
    imgSrc: "/assets/pictures/technology_defensive/cannon-emplacement.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Boiling Oil",
    age: "3",
    imgSrc: "/assets/pictures/technology_defensive/boiling-oil.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Court Architects",
    age: "4",
    imgSrc: "/assets/pictures/technology_defensive/court-architects.png",
    civ: civs.exceptMany(["MON"]),
    class: "tech",
  },
  {
    title: "Fortify Outpost",
    age: "2",
    imgSrc: "/assets/pictures/technology_defensive/fortify-outpost.png",
    civ: civs.exceptMany(["MON", "RUS"]),
    class: "tech",
  },
  {
    title: "Extra Hammocks",
    age: "31",
    imgSrc: "/assets/pictures/technology_chinese/extra-hammocks.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Naval Arrowslits",
    age: "2",
    imgSrc: "/assets/pictures/technology_naval/naval-arrow-slits.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Composite Bows",
    age: "3",
    imgSrc: "/assets/pictures/technology_abbasid/composite-bows.png",
    civ: ["ABB"],
    class: "tech",
  },
  {
    title: "Camel Rider Barding",
    age: "4",
    imgSrc: "/assets/pictures/technology_abbasid/camel-rider-barding-4.png",
    civ: ["ABB"],
    class: "tech",
  },
  {
    title: "Camel Handling",
    age: "3",
    imgSrc: "/assets/pictures/technology_abbasid/camel-handling.png",
    civ: ["ABB"],
    class: "tech",
  },
  {
    title: "Camel Support",
    age: "4",
    imgSrc: "/assets/pictures/technology_abbasid/camel-support.png",
    civ: ["ABB"],
    class: "tech",
  },
  {
    title: "Camel Rider Shields",
    age: "3",
    imgSrc: "/assets/pictures/technology_abbasid/camel-rider-shields.png",
    civ: ["ABB"],
    class: "tech",
  },
  {
    title: "Medical Centers",
    age: "3",
    imgSrc: "/assets/pictures/technology_abbasid/medical-centers.png",
    civ: ["ABB"],
    class: "tech",
  },
  {
    title: "Boot Camp",
    age: "2",
    imgSrc: "/assets/pictures/technology_abbasid/boot-camp.png",
    civ: ["ABB"],
    class: "tech",
  },
  {
    title: "Teak Masts",
    age: "3",
    imgSrc: "/assets/pictures/technology_abbasid/teak-masts.png",
    civ: ["ABB", "AYY"],
    class: "tech",
  },
  {
    title: "Copper Plating",
    age: "3",
    imgSrc: "/assets/pictures/technology_japanese/copper-plating-3.png",
    civ: ["JAP"],
    class: "tech",
  },
  {
    title: "Reinforcement",
    age: "1",
    imgSrc: "/assets/pictures/technology_ayyubids/military-wing-reinforcement-1.png",
    civ: ["AYY"],
    class: "tech",
  },
  {
    title: "Master Smiths",
    age: "1",
    imgSrc: "/assets/pictures/technology_ayyubids/military-wing-master-smiths-1.png",
    civ: ["AYY"],
    class: "tech",
  },
  {
    title: "Siege Carpentry",
    age: "3",
    imgSrc: "/assets/pictures/technology_ayyubids/siege-carpentry-3.png",
    civ: ["AYY"],
    class: "tech",
  },
  {
    title: "Siege Carpentry",
    age: "3",
    imgSrc: "/assets/pictures/technology_ayyubids/sultans-mamluks-3.png",
    civ: ["AYY"],
    class: "tech",
  },
  {
    title: "Infantry Support",
    age: "4",
    imgSrc: "/assets/pictures/technology_ayyubids/infantry-support-4.png",
    civ: ["AYY"],
    class: "tech",
  },
  {
    title: "Proselytization",
    age: "4",
    imgSrc: "/assets/pictures/technology_abbasid/faith.png",
    civ: ["ABB"],
    class: "tech",
  },
  {
    title: "Phalanx",
    age: "2",
    imgSrc: "/assets/pictures/technology_abbasid/phalanx.png",
    civ: ["ABB", "AYY"],
    class: "tech",
  },
  {
    title: "Pyrotechnics",
    age: "4",
    imgSrc: "/assets/pictures/technology_chinese/pyrotechnics.png",
    civ: ["CHI"],
    class: "tech",
  },
  {
    title: "Reload Drills",
    age: "4",
    imgSrc: "/assets/pictures/technology_chinese/reload-drills.png",
    civ: ["CHI"],
    class: "tech",
  },
  {
    title: "Reusable Barrels",
    age: "4",
    imgSrc: "/assets/pictures/technology_chinese/reusable-barrels.png",
    civ: ["CHI"],
    class: "tech",
  },
  {
    title: "Battle Hardened",
    age: "4",
    imgSrc: "/assets/pictures/technology_chinese/battle-hardened.png",
    civ: ["CHI"],
    class: "tech",
  },
  {
    title: "Handcannon Slits",
    age: "2",
    imgSrc: "/assets/pictures/technology_chinese/handcannon-slits.png",
    civ: ["CHI", "ZXL"],
    class: "tech",
  },
  {
    title: "Thunderclap Bombs",
    age: "4",
    imgSrc: "/assets/pictures/technology_chinese/thunderclap-bombs-4.png",
    civ: ["CHI", "ZXL"],
    class: "tech",
  },
  {
    title: "Cloud of Terror",
    age: "4",
    imgSrc: "/assets/pictures/technology_zhuxi/cloud-of-terror-4.png",
    civ: ["ZXL"],
    class: "tech",
  },
  {
    title: "Roar of the Dragon",
    age: "4",
    imgSrc: "/assets/pictures/technology_zhuxi/roar-of-the-dragon-4.png",
    civ: ["ZXL"],
    class: "tech",
  },
  {
    title: "Military Affairs Bureau",
    age: "4",
    imgSrc: "/assets/pictures/technology_zhuxi/military-affairs-bureau-1.png",
    civ: ["ZXL"],
    class: "tech",
  },
  {
    title: "10000 Bolts",
    age: "4",
    imgSrc: "/assets/pictures/technology_zhuxi/10000-bolts-4.png",
    civ: ["ZXL"],
    class: "tech",
  },
  {
    title: "Dynastic Protectors",
    age: "4",
    imgSrc: "/assets/pictures/technology_zhuxi/dynastic-protectors-4.png",
    civ: ["ZXL"],
    class: "tech",
  },
  {
    title: "Armored Beasts",
    age: "4",
    imgSrc: "/assets/pictures/technology_delhi/armored-beasts.png",
    civ: ["DEL"],
    class: "tech",
  },
  {
    title: "Efficient Production",
    age: "1",
    imgSrc: "/assets/pictures/technology_delhi/efficient-production.png",
    civ: ["DEL"],
    class: "tech",
  },
  {
    title: "Howdahs",
    age: "4",
    imgSrc: "/assets/pictures/technology_delhi/siege-elephant.png",
    civ: ["DEL"],
    class: "tech",
  },
  {
    title: "Forced March",
    age: "3",
    imgSrc: "/assets/pictures/technology_delhi/forced-march.png",
    civ: ["DEL"],
    class: "tech",
  },
  {
    title: "Zeal",
    age: "4",
    imgSrc: "/assets/pictures/technology_delhi/zeal.png",
    civ: ["DEL"],
    class: "tech",
  },
  {
    title: "Honed Blades",
    age: "3",
    imgSrc: "/assets/pictures/technology_delhi/honed-blades.png",
    civ: ["DEL"],
    class: "tech",
  },
  {
    title: "Tranquil Venue",
    age: "3",
    imgSrc: "/assets/pictures/technology_delhi/tranquil-venue.png",
    civ: ["DEL"],
    class: "tech",
  },
  {
    title: "Lookout Towers",
    age: "3",
    imgSrc: "/assets/pictures/technology_delhi/lookout-towers.png",
    civ: ["DEL"],
    class: "tech",
  },
  {
    title: "Slow-Burning Defenses",
    age: "4",
    imgSrc: "/assets/pictures/technology_delhi/slow-burning-defenses.png",
    civ: ["DEL"],
    class: "tech",
  },
  {
    title: "Manuscript Trade",
    age: "1",
    imgSrc: "/assets/pictures/technology_delhi/manuscript-trade-1.png",
    civ: ["DEL"],
    class: "tech",
  },
  {
    title: "Crossbow Stirrups",
    age: "4",
    imgSrc: "/assets/pictures/technology_french/crossbow-stirrups.png",
    civ: ["FRE", "JDA"],
    class: "tech",
  },
  {
    title: "Gambesons",
    age: "3",
    imgSrc: "/assets/pictures/technology_french/gambesons.png",
    civ: ["FRE", "JDA"],
    class: "tech",
  },
  {
    title: "Chivalry",
    age: "2",
    imgSrc: "/assets/pictures/technology_french/chivalry.png",
    civ: ["FRE", "JDA"],
    class: "tech",
  },
  {
    title: "Companion Equipment",
    age: "3",
    imgSrc: "/assets/pictures/technology_jeanne/companion-equipment-3.png",
    civ: ["FRE", "JDA"],
    class: "tech",
  },
  {
    title: "Ordinance Company",
    age: "3",
    imgSrc: "/assets/pictures/technology_jeanne/ordinance-company-3.png",
    civ: ["FRE", "JDA"],
    class: "tech",
  },
  {
    title: "Royal Bloodlines",
    age: "4",
    imgSrc: "/assets/pictures/technology_french/royal-bloodlines.png",
    civ: ["FRE", "JDA"],
    class: "tech",
  },
  {
    title: "Cantled Saddles",
    age: "3",
    imgSrc: "/assets/pictures/technology_french/cantled-saddles.png",
    civ: ["FRE", "JDA"],
    class: "tech",
  },
  {
    title: "Long Guns",
    age: "3",
    imgSrc: "/assets/pictures/technology_french/long-guns.png",
    civ: ["FRE", "JDA"],
    class: "tech",
  },
  {
    title: "Slate and Stone Construction",
    age: "3",
    imgSrc:
      "/assets/pictures/technology_hre/slate-and-stone-construction.png",
    civ: ["HRE", "DRA"],
    class: "tech",
  },
  {
    title: "Reinforced Defenses",
    age: "4",
    imgSrc: "/assets/pictures/technology_hre/reinforced-defenses.png",
    civ: ["HRE", "DRA"],
    class: "tech",
  },
  {
    title: "Marching Drills",
    age: "2",
    imgSrc: "/assets/pictures/technology_hre/marching-drills.png",
    civ: ["HRE"],
    class: "tech",
  },
  {
    title: "Heavy Maces",
    age: "3",
    imgSrc: "/assets/pictures/technology_hre/heavy-maces.png",
    civ: ["HRE"],
    class: "tech",
  },
  {
    title: "Two-Handed Weapons",
    age: "3",
    imgSrc: "/assets/pictures/technology_hre/two-handed-weapon.png",
    civ: ["HRE"],
    class: "tech",
  },
  {
    title: "Fire Stations",
    age: "2",
    imgSrc: "/assets/pictures/technology_hre/fire-stations.png",
    civ: ["HRE", "DRA"],
    class: "tech",
  },
  {
    title: "Inspired Warriors",
    age: "3",
    imgSrc: "/assets/pictures/technology_hre/inspired-warriors.png",
    civ: ["HRE", "DRA"],
    class: "tech",
  },
  {
    title: "Riveted Chain Mail",
    age: "4",
    imgSrc: "/assets/pictures/technology_hre/riveted-chain-mail-2.png",
    civ: ["HRE"],
    class: "tech",
  },
  {
    title: "Steel Barding",
    age: "4",
    imgSrc: "/assets/pictures/technology_hre/steel-barding-3.png",
    civ: ["HRE"],
    class: "tech",
  },
  {
    title: "Network of Citadels",
    age: "3",
    imgSrc: "/assets/pictures/technology_english/network-of-citadels.png",
    civ: ["ENG"],
    class: "tech",
  },
  {
    title: "Arrow Volley",
    age: "4",
    imgSrc: "/assets/pictures/technology_english/arrow-volley.png",
    civ: ["ENG"],
    class: "tech",
  },
  {
    title: "Setup Camp",
    age: "2",
    imgSrc: "/assets/pictures/technology_english/setup-camp.png",
    civ: ["ENG"],
    class: "tech",
  },
  {
    title: "Armor Clad",
    age: "3",
    imgSrc: "/assets/pictures/technology_english/armor-clad.png",
    civ: ["ENG"],
    class: "tech",
  },
  {
    title: "Admiralty",
    age: "2",
    imgSrc: "/assets/pictures/technology_english/admiralty-2.png",
    civ: ["ENG"],
    class: "tech",
  },
  {
    title: "Shattering Projectiles",
    age: "4",
    imgSrc: "/assets/pictures/technology_english/shattering-projectiles.png",
    civ: ["ENG"],
    class: "tech",
  },
  {
    title: "Banco Repairs",
    age: "2",
    imgSrc: "/assets/pictures/technology_malians/banco-repairs-2.png",
    civ: ["MAL"],
    class: "tech",
  },
  {
    title: "Farima Leadership",
    age: "4",
    imgSrc: "/assets/pictures/technology_malians/farima-leadership-4.png",
    civ: ["MAL"],
    class: "tech",
  },
  {
    title: "Imported Armor",
    age: "3",
    imgSrc: "/assets/pictures/technology_malians/imported-armor-3.png",
    civ: ["MAL"],
    class: "tech",
  },
  {
    title: "Local Knowledge",
    age: "3",
    imgSrc: "/assets/pictures/technology_malians/local-knowledge-4.png",
    civ: ["MAL"],
    class: "tech",
  },
  {
    title: "Poisoned Arrows",
    age: "3",
    imgSrc: "/assets/pictures/technology_malians/poisoned-arrows-3.png",
    civ: ["MAL"],
    class: "tech",
  },
  {
    title: "Precision Training",
    age: "3",
    imgSrc: "/assets/pictures/technology_malians/precision-training-4.png",
    civ: ["MAL"],
    class: "tech",
  },
  {
    title: "Canoe Tactics",
    age: "2",
    imgSrc: "/assets/pictures/technology_malians/canoe-tactics-2.png",
    civ: ["MAL"],
    class: "tech",
  },
  {
    title: "Whistling Arrows",
    age: "2",
    imgSrc: "/assets/pictures/technology_mongols/whistling-arrows.png",
    civ: ["MON"],
    class: "tech",
  },
  {
    title: "Yam Network",
    age: "3",
    imgSrc: "/assets/pictures/technology_mongols/yam-network.png",
    civ: ["MON"],
    class: "tech",
  },
  {
    title: "Additional Torches",
    age: "3",
    imgSrc: "/assets/pictures/technology_mongols/additional-torches.png",
    civ: ["MON"],
    class: "tech",
  },
  {
    title: "Steppe Lancers",
    age: "4",
    imgSrc: "/assets/pictures/technology_mongols/steppe-lancers.png",
    civ: ["MON"],
    class: "tech",
  },
  {
    title: "Monastic Shrines",
    age: "4",
    imgSrc: "/assets/pictures/technology_mongols/monastic-shrines.png",
    civ: ["MON"],
    class: "tech",
  },
  {
    title: "Siha Bow Limbs",
    age: "3",
    imgSrc: "/assets/pictures/technology_mongols/siha-bow-limbs.png",
    civ: ["MON"],
    class: "tech",
  },
  {
    title: "Armored Hull",
    age: "3",
    imgSrc: "/assets/pictures/technology_naval/armored-hull.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Shipwrights",
    age: "3",
    imgSrc: "/assets/pictures/technology_naval/shipwrights-4.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Springald Crews",
    age: "3",
    imgSrc: "/assets/pictures/technology_naval/springald-crews-3.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Incendiaries",
    age: "3",
    imgSrc: "/assets/pictures/technology_naval/incendiaries-3.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Herbal Medicine",
    age: "3",
    imgSrc: "/assets/pictures/technology_religious/herbal-medicine.png",
    civ: civs.except("JAP"),
    class: "tech",
  },
  {
    title: "Piety",
    age: "4",
    imgSrc: "/assets/pictures/technology_religious/piety.png",
    civ: civs.except("JAP"),
    class: "tech",
  },
  {
    title: "Shinto Rituals",
    age: "3",
    imgSrc: "/assets/pictures/technology_japanese/shinto_rituals.png",
    civ: ["JAP"],
    class: "tech",
  },
  {
    title: "Gion Festival",
    age: "3",
    imgSrc: "/assets/pictures/technology_japanese/gion_festival.png",
    civ: ["JAP"],
    class: "tech",
  },
  {
    title: "Bunrei",
    age: "3",
    imgSrc: "/assets/pictures/technology_japanese/bunrei.png",
    civ: ["JAP"],
    class: "tech",
  },
  {
    title: "Zen",
    age: "3",
    imgSrc: "/assets/pictures/technology_japanese/zen.png",
    civ: ["JAP"],
    class: "tech",
  },
  {
    title: "Nehan",
    age: "3",
    imgSrc: "/assets/pictures/technology_japanese/nehan.png",
    civ: ["JAP"],
    class: "tech",
  },
  {
    title: "Five Mountain Ministries",
    age: "3",
    imgSrc: "/assets/pictures/technology_japanese/five_ministries.png",
    civ: ["JAP"],
    class: "tech",
  },
  {
    title: "Tithe Barns",
    age: "4",
    imgSrc: "/assets/pictures/technology_religious/tithe-barns.png",
    civ: civs.except("JAP"),
    class: "tech",
  },
  {
    title: "Janissary Guns",
    age: "4",
    imgSrc: "/assets/pictures/technology_ottomans/janissary-guns-4.png",
    civ: ["OTT"],
    class: "tech",
  },
  {
    title: "Imperial Fleet",
    age: "4",
    imgSrc: "/assets/pictures/technology_ottomans/imperial-fleet-4.png",
    civ: ["OTT"],
    class: "tech",
  },
  {
    title: "Advanced Academy",
    age: "1",
    imgSrc: "/assets/pictures/technology_ottomans/advanced-academy-1.png",
    civ: ["OTT"],
    class: "tech",
  },
  {
    title: "Fast Training",
    age: "1",
    imgSrc: "/assets/pictures/technology_ottomans/fast-training-1.png",
    civ: ["OTT"],
    class: "tech",
  },
  {
    title: "Field Work",
    age: "1",
    imgSrc: "/assets/pictures/technology_ottomans/field-work-1.png",
    civ: ["OTT"],
    class: "tech",
  },
  {
    title: "Janissary Company",
    age: "1",
    imgSrc: "/assets/pictures/technology_ottomans/janissary-company-1.png",
    civ: ["OTT"],
    class: "tech",
  },
  {
    title: "Mehter Drums",
    age: "1",
    imgSrc: "/assets/pictures/technology_ottomans/mehter-drums-1.png",
    civ: ["OTT"],
    class: "tech",
  },
  {
    title: "Military Campus",
    age: "1",
    imgSrc: "/assets/pictures/technology_ottomans/military-campus-1.png",
    civ: ["OTT"],
    class: "tech",
  },
  {
    title: "Siege Crews",
    age: "1",
    imgSrc: "/assets/pictures/technology_ottomans/siege-crews-1.png",
    civ: ["OTT"],
    class: "tech",
  },
  {
    title: "Great Bombard Emplacement",
    age: "4",
    imgSrc:
      "/assets/pictures/technology_ottomans/great-bombard-emplacement.png",
    civ: ["OTT"],
    class: "tech",
  },
  {
    title: "Fine Tuned Guns",
    age: "4",
    imgSrc: "/assets/pictures/technology_rus/fine-tuned-guns.png",
    civ: ["RUS"],
    class: "tech",
  },
  {
    title: "Boyar's Fortitude",
    age: "3",
    imgSrc: "/assets/pictures/technology_rus/boyars-fortitude.png",
    civ: ["RUS"],
    class: "tech",
  },
  {
    title: "Mounted Training",
    age: "4",
    imgSrc: "/assets/pictures/technology_rus/mounted-training.png",
    civ: ["RUS"],
    class: "tech",
  },
  {
    title: "Knight Sabers",
    age: "4",
    imgSrc: "/assets/pictures/technology_rus/knight-sabers.png",
    civ: ["RUS"],
    class: "tech",
  },
  {
    title: "Siege Crew Training",
    age: "4",
    imgSrc: "/assets/pictures/technology_rus/siege-crew-training.png",
    civ: ["RUS"],
    class: "tech",
  },
  {
    title: "Wandering Town",
    age: "4",
    imgSrc: "/assets/pictures/technology_rus/wandering-town.png",
    civ: ["RUS"],
    class: "tech",
  },
  {
    title: "Warrior Scout",
    age: "2",
    imgSrc: "/assets/pictures/technology_rus/warrior_scout_2.png",
    civ: ["RUS"],
    class: "tech",
  },
  {
    title: "Divine Light",
    age: "3",
    imgSrc: "/assets/pictures/technology_rus/blessing-duration.png",
    civ: ["RUS"],
    class: "tech",
  },
  {
    title: "Fervor",
    age: "3",
    imgSrc: "/assets/pictures/technology_rus/improved-blessing.png",
    civ: ["RUS"],
    class: "tech",
  },
  {
    title: "Saint's Veneration",
    age: "4",
    imgSrc: "/assets/pictures/technology_rus/saints-veneration-4.png",
    civ: ["RUS"],
    class: "tech",
  },
  {
    title: "Banded Arms",
    age: "4",
    imgSrc: "/assets/pictures/technology_rus/banded-arms.png",
    civ: ["RUS"],
    class: "tech",
  },
  {
    title: "Double Time",
    age: "4",
    imgSrc: "/assets/pictures/technology_rus/double-time.png",
    civ: ["RUS"],
    class: "tech",
  },
  {
    title: "Castle Watch",
    age: "2",
    imgSrc: "/assets/pictures/technology_rus/castle-watch.png",
    civ: ["RUS"],
    class: "tech",
  },
  {
    title: "Castle Turret",
    age: "2",
    imgSrc: "/assets/pictures/technology_rus/castle-turret.png",
    civ: ["RUS"],
    class: "tech",
  },
  {
    title: "Adaptable Hulls",
    age: "2",
    imgSrc: "/assets/pictures/technology_rus/adaptable-hulls-3.png",
    civ: ["RUS"],
    class: "tech",
  },
  {
    title: "Heavy Dromon",
    age: "3",
    imgSrc: "/assets/pictures/technology_byzantines/heavy-dromon-3.png",
    civ: ["BYZ"],
    class: "tech",
  },
  {
    title: "Liquid Explosives",
    age: "3",
    imgSrc: "/assets/pictures/technology_byzantines/liquid-explosives-3.png",
    civ: ["BYZ"],
    class: "tech",
  },
  {
    title: "Eastern Mercenary Contract",
    age: "1",
    imgSrc: "/assets/pictures/technology_byzantines/eastern-mercenary-contract-1.png",
    civ: ["BYZ"],
    class: "tech",
  },
  {
    title: "Silk Road Mercenary Contract",
    age: "1",
    imgSrc: "/assets/pictures/technology_byzantines/silk-road-mercenary-contract-1.png",
    civ: ["BYZ"],
    class: "tech",
  },
  {
    title: "Western Mercenary Contract",
    age: "1",
    imgSrc: "/assets/pictures/technology_byzantines/western-mercenary-contract-1.png",
    civ: ["BYZ"],
    class: "tech",
  },
  {
    title: "Veteran Contract",
    age: "3",
    imgSrc: "/assets/pictures/technology_byzantines/veteran-mercenaries-3.png",
    civ: ["BYZ"],
    class: "tech",
  },
  {
    title: "Elite Contract",
    age: "4",
    imgSrc: "/assets/pictures/technology_byzantines/elite-mercenaries-4.png",
    civ: ["BYZ"],
    class: "tech",
  },
  {
    title: "Explosives",
    age: "4",
    imgSrc: "/assets/pictures/technology_japanese/explosives-4.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Heated Shot",
    age: "4",
    imgSrc: "/assets/pictures/technology_japanese/heated-shot-4.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Swivel Cannon",
    age: "4",
    imgSrc: "/assets/pictures/technology_japanese/swivel-cannon-4.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Oda Tactics",
    age: "4",
    imgSrc: "/assets/pictures/technology_japanese/oda-tactics-4.png",
    civ: ["JAP"],
    class: "tech",
  },
  {
    title: "Daimyo Manor",
    age: "1",
    imgSrc: "/assets/pictures/technology_japanese/daimyo-manor-1.png",
    civ: ["JAP"],
    class: "tech",
  },
  {
    title: "Daimyo Palace",
    age: "2",
    imgSrc: "/assets/pictures/technology_japanese/daimyo-palace-2.png",
    civ: ["JAP"],
    class: "tech",
  },
  {
    title: "Shogunate Castle",
    age: "3",
    imgSrc: "/assets/pictures/technology_japanese/shogunate-castle-3.png",
    civ: ["JAP"],
    class: "tech",
  },
  {
    title: "Kabura-ya Whistling Arrow",
    age: "3",
    imgSrc: "/assets/pictures/technology_japanese/kabura-ya-whistling-arrow-3.png",
    civ: ["JAP"],
    class: "tech",
  },
  {
    title: "Odachi",
    age: "3",
    imgSrc: "/assets/pictures/technology_japanese/odachi-3.png",
    civ: ["JAP"],
    class: "tech",
  },
  {
    title: "Border Settlements",
    age: "2",
    imgSrc: "/assets/pictures/technology_byzantines/border-settlements-2.png",
    civ: ["BYZ"],
    class: "tech",
  },
  {
    title: "Expilatores",
    age: "2",
    imgSrc: "/assets/pictures/technology_byzantines/expilatores-2.png",
    civ: ["BYZ"],
    class: "tech",
  },
  {
    title: "Trapezites",
    age: "2",
    imgSrc: "/assets/pictures/technology_byzantines/trapezites-2.png",
    civ: ["BYZ"],
    class: "tech",
  },
  {
    title: "Greek Fire Projectiles",
    age: "4",
    imgSrc: "/assets/pictures/technology_byzantines/greek-fire-projectiles-4.png",
    civ: ["BYZ"],
    class: "tech",
  },
  {
    title: "Numeri",
    age: "4",
    imgSrc: "/assets/pictures/technology_byzantines/numeri-4.png",
    civ: ["BYZ"],
    class: "tech",
  },
  {
    title: "Teardrop Shields",
    age: "3",
    imgSrc: "/assets/pictures/technology_byzantines/teardrop-shields-3.png",
    civ: ["BYZ"],
    class: "tech",
  },
  {
    title: "Ferocious Speed",
    age: "4",
    imgSrc: "/assets/pictures/technology_byzantines/ferocious-speed-4.png",
    civ: ["BYZ"],
    class: "tech",
  },
];
