//Composables
import { civs } from "@/composables/builds/icons/civs.js";

//Exported methods
export const techEco = [
  {
    title: "Double Broadaxe",
    age: "2",
    imgSrc: "/assets/pictures/technology_economy/double-broadaxe.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Lumber Preservation",
    age: "3",
    imgSrc: "/assets/pictures/technology_economy/lumber-preservation.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Crosscut Saw",
    age: "4",
    imgSrc: "/assets/pictures/technology_economy/crosscut-saw.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Forestry",
    age: "1",
    imgSrc: "/assets/pictures/technology_economy/forestry.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Horticulture",
    age: "2",
    imgSrc: "/assets/pictures/technology_economy/horticulture.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Fertilization",
    age: "3",
    imgSrc: "/assets/pictures/technology_economy/fertilization.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Precision Cross-Breeding",
    age: "4",
    imgSrc:
      "/assets/pictures/technology_economy/precision-cross-breeding.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Wheelbarrow",
    age: "1",
    imgSrc: "/assets/pictures/technology_economy/wheelbarrow.png",
    civ: civs.except("JAP"),
    class: "tech",
  },
  {
    title: "Specialized Pick",
    age: "2",
    imgSrc: "/assets/pictures/technology_economy/specialized-pick.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Acid Distillation",
    age: "3",
    imgSrc: "/assets/pictures/technology_economy/acid-distilization.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Cupellation",
    age: "4",
    imgSrc: "/assets/pictures/technology_economy/cupellation.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Textiles",
    age: "2",
    imgSrc: "/assets/pictures/technology_economy/textiles.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Survival Techniques",
    age: "1",
    imgSrc: "/assets/pictures/technology_economy/survival-techniques.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Professional Scouts",
    age: "2",
    imgSrc: "/assets/pictures/technology_economy/professional-scouts.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Extended Lines",
    age: "2",
    imgSrc: "/assets/pictures/technology_economy/extended-lines.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Drift Nets",
    age: "3",
    imgSrc: "/assets/pictures/technology_economy/drift-nets.png",
    civ: civs,
    class: "tech",
  },
  {
    title: "Advancement",
    age: "1",
    imgSrc:
      "/assets/pictures/technology_ayyubids/culture-wing-advancement-1.png",
    civ: ["AYY"],
    class: "tech",
  },
  {
    title: "Imperial Red Seals",
    age: "3",
    imgSrc:
      "/assets/pictures/technology_zhuxi/imperial-red-seals-3.png",
    civ: ["ZXL"],
    class: "tech",
  },
  {
    title: "Advanced Administration",
    age: "4",
    imgSrc:
      "/assets/pictures/technology_zhuxi/advanced-administration-4.png",
    civ: ["ZXL"],
    class: "tech",
  },
  {
    title: "Logistics",
    age: "1",
    imgSrc:
      "/assets/pictures/technology_ayyubids/culture-wing-logistics-1.png",
    civ: ["AYY"],
    class: "tech",
  },
  {
    title: "Growth",
    age: "1",
    imgSrc:
      "/assets/pictures/technology_ayyubids/economic-wing-growth-1.png",
    civ: ["AYY"],
    class: "tech",
  },
  {
    title: "Merchant Guilds",
    age: "4",
    imgSrc:
      "/assets/pictures/technology_french/merchant-guilds-4.png",
    civ: ["FRE", "JDA"],
    class: "tech",
  },
  {
    title: "Industry",
    age: "1",
    imgSrc:
      "/assets/pictures/technology_ayyubids/economic-wing-industry-1.png",
    civ: ["AYY"],
    class: "tech",
  },
  {
    title: "Advisors",
    age: "1",
    imgSrc:
      "/assets/pictures/technology_ayyubids/trade-wing-advisors-1.png",
    civ: ["AYY"],
    class: "tech",
  },
  {
    title: "Bazaar",
    age: "1",
    imgSrc:
      "/assets/pictures/technology_ayyubids/trade-wing-bazaar-1.png",
    civ: ["AYY"],
    class: "tech",
  },
  {
    title: "Towara",
    age: "1",
    imgSrc:
      "/assets/pictures/technology_japanese/towara-1.png",
    civ: ["JAP"],
    class: "tech",
  },
  {
    title: "Takezaiku",
    age: "2",
    imgSrc:
      "/assets/pictures/technology_japanese/takezaiku-2.png",
    civ: ["JAP"],
    class: "tech",
  },
  {
    title: "Fudasashi",
    age: "3",
    imgSrc:
      "/assets/pictures/technology_japanese/fudasashi-3.png",
    civ: ["JAP"],
    class: "tech",
  },
  {
    title: "Improved Processing",
    age: "1",
    imgSrc: "/assets/pictures/technology_abbasid/improved-processing.png",
    civ: ["ABB"],
    class: "tech",
  },
  {
    title: "Agriculture",
    age: "3",
    imgSrc: "/assets/pictures/technology_abbasid/agriculture.png",
    civ: ["ABB"],
    class: "tech",
  },
  {
    title: "Preservation of Knowledge",
    age: "2",
    imgSrc:
      "/assets/pictures/technology_abbasid/preservation-of-knowledge.png",
    civ: ["ABB"],
    class: "tech",
  },
  {
    title: "Armored Caravans",
    age: "3",
    imgSrc: "/assets/pictures/technology_abbasid/armored-caravans.png",
    civ: ["ABB"],
    class: "tech",
  },
  {
    title: "Grand Bazaar",
    age: "2",
    imgSrc: "/assets/pictures/technology_abbasid/grand-bazaar.png",
    civ: ["ABB"],
    class: "tech",
  },
  {
    title: "Spice Roads",
    age: "4",
    imgSrc: "/assets/pictures/technology_abbasid/spice-roads.png",
    civ: ["ABB"],
    class: "tech",
  },
  {
    title: "Fresh Foodstuffs",
    age: "2",
    imgSrc: "/assets/pictures/technology_abbasid/fresh-foodstuffs.png",
    civ: ["ABB"],
    class: "tech",
  },
  {
    title: "Fertile Crescent",
    age: "2",
    imgSrc: "/assets/pictures/technology_abbasid/fertile-crescent-2.png",
    civ: ["ABB"],
    class: "tech",
  },
  {
    title: "Extra Materials",
    age: "3",
    imgSrc: "/assets/pictures/technology_chinese/extra-materials.png",
    civ: ["CHI"],
    class: "tech",
  },
  {
    title: "Ancient Techniques",
    age: "4",
    imgSrc: "/assets/pictures/technology_chinese/ancient-techniques.png",
    civ: ["CHI"],
    class: "tech",
  },
  {
    title: "Imperial Examinations",
    age: "2",
    imgSrc: "/assets/pictures/technology_chinese/imperial-examination.png",
    civ: ["CHI"],
    class: "tech",
  },
  {
    title: "Village Fortresses",
    age: "3",
    imgSrc: "/assets/pictures/technology_delhi/village-fortresses.png",
    civ: ["DEL"],
    class: "tech",
  },
  {
    title: "Reinforced Foundations",
    age: "3",
    imgSrc: "/assets/pictures/technology_delhi/reinforced-foundations.png",
    civ: ["DEL"],
    class: "tech",
  },
  {
    title: "All-Seeing Eye",
    age: "2",
    imgSrc: "/assets/pictures/technology_delhi/all-seeing-eye.png",
    civ: ["DEL"],
    class: "tech",
  },
  {
    title: "Sanctity",
    age: "2",
    imgSrc: "/assets/pictures/technology_delhi/sanctity.png",
    civ: ["DEL"],
    class: "tech",
  },
  {
    title: "Swiftness",
    age: "3",
    imgSrc: "/assets/pictures/technology_delhi/swiftness.png",
    civ: ["DEL"],
    class: "tech",
  },
  {
    title: "Hearty Rations",
    age: "3",
    imgSrc: "/assets/pictures/technology_delhi/hearty-rations.png",
    civ: ["DEL"],
    class: "tech",
  },
  {
    title: "Enclosures",
    age: "4",
    imgSrc: "/assets/pictures/technology_english/enclosures.png",
    civ: ["ENG"],
    class: "tech",
  },
  {
    title: "Enlistment Incentives",
    age: "4",
    imgSrc: "/assets/pictures/technology_french/enlistment-incentives.png",
    civ: ["FRE", "JDA"],
    class: "tech",
  },
  {
    title: "Benediction",
    age: "3",
    imgSrc: "/assets/pictures/technology_hre/benediction.png",
    civ: ["HRE", "DRA"],
    class: "tech",
  },
  {
    title: "Devoutness",
    age: "3",
    imgSrc: "/assets/pictures/technology_hre/devoutness.png",
    civ: ["HRE", "DRA"],
    class: "tech",
  },
  {
    title: "Piracy",
    age: "2",
    imgSrc: "/assets/pictures/technology_mongols/piracy.png",
    civ: ["MON"],
    class: "tech",
  },
  {
    title: "Superior Mobility",
    age: "1",
    imgSrc: "/assets/pictures/technology_mongols/superior-mobility.png",
    civ: ["MON"],
    class: "tech",
  },
  {
    title: "Raid Bounty",
    age: "2",
    imgSrc: "/assets/pictures/technology_mongols/raid-bounty.png",
    civ: ["MON"],
    class: "tech",
  },
  {
    title: "Stone Bounty",
    age: "4",
    imgSrc: "/assets/pictures/technology_mongols/stone-bounty.png",
    civ: ["MON"],
    class: "tech",
  },
  {
    title: "Stone Commerce",
    age: "4",
    imgSrc: "/assets/pictures/technology_mongols/stone-commerce.png",
    civ: ["MON"],
    class: "tech",
  },
  {
    title: "Anatolian Hills",
    age: "1",
    imgSrc: "/assets/pictures/technology_ottomans/anatolian-hills-1.png",
    civ: ["OTT"],
    class: "tech",
  },
  {
    title: "Trade Bags",
    age: "1",
    imgSrc: "/assets/pictures/technology_ottomans/trade-bags-1.png",
    civ: ["OTT"],
    class: "tech",
  },
];
