//Exported methods
export const unitReligious = [
  {
    title: "Monk",
    age: "3",
    imgSrc: "/assets/pictures/unit_religious/monk-3.png",
    civ: ["ENG", "FRE", "JDA", "RUS", "MAL", "MON", "CHI", "ZXL", "HRE", "DRA", "BYZ"],
    class: "military",
    shorthand: ["monk"],
  },
  {
    title: "Shaolin Monk",
    age: "3",
    imgSrc: "/assets/pictures/unit_zhuxi/shaolin-monk-3.png",
    civ: ["ZXL"],
    class: "military",
  },
  {
    title: "Imam",
    age: "3",
    imgSrc: "/assets/pictures/unit_abbasid/imam.png",
    civ: ["ABB", "OTT"],
    class: "military",
  },
  {
    title: "Dervish",
    age: "3",
    imgSrc: "/assets/pictures/unit_ayyubids/dervish-3.png",
    civ: ["AYY"],
    class: "military",
  },
  {
    title: "Scholar",
    age: "1",
    imgSrc: "/assets/pictures/unit_delhi/scholar.png",
    civ: ["DEL"],
    class: "military",
  },
  {
    title: "Buddhist Monk",
    age: "3",
    imgSrc: "/assets/pictures/unit_japanese/buddhist-monk-3.png",
    civ: ["JAP"],
    class: "military",
  },
  {
    title: "Shinto Priest",
    age: "3",
    imgSrc: "/assets/pictures/unit_japanese/shinto-priest-3.png",
    civ: ["JAP"],
    class: "military",
  },
  {
    title: "Prelate",
    age: "1",
    imgSrc: "/assets/pictures/unit_hre/prelate.png",
    civ: ["HRE", "DRA"],
    class: "military",
  },
  {
    title: "Shaman",
    age: "1",
    imgSrc: "/assets/pictures/unit_mongols/shaman.png",
    civ: ["MON"],
    class: "military",
  },
];
