//Exported methods
export const unitEco = [
  {
    title: "Villager",
    age: 1,
    imgSrc: "/assets/pictures/unit_worker/villager.png",
    civ: ["BYZ", "DRA", "ENG", "FRE", "HRE", "JDA", "RUS"],
    class: "default",
    shorthand: "vil",
    costs: {
      food: 50,
      wood: 0,
      stone: 0,
      gold: 0,
      vizier: 0,
      oliveoil: 0,
      total: 50,
      popcap: 1,
      time: 20,
    },
    description:
      "Gathers Wood, Food, Stone, and Gold. Builds and repairs buildings and can repair siege engines and naval units.\n- Weak in combat",
    id: "villager-1",
  },
  {
    title: "Villager",
    age: 1,
    imgSrc: "/assets/pictures/unit_worker/villager-delhi.png",
    civ: ["DEL"],
    class: "default",
    costs: {
      food: 50,
      wood: 0,
      stone: 0,
      gold: 0,
      vizier: 0,
      oliveoil: 0,
      total: 50,
      popcap: 1,
      time: 20,
    },
    description:
      "Gathers Wood, Food, Stone, and Gold. Builds and repairs buildings and can repair siege engines and naval units.\n- Weak in combat",
    id: "villager-1",
  },
  {
    title: "Villager",
    age: 1,
    imgSrc: "/assets/pictures/unit_worker/villager-japanese.png",
    civ: ["JAP"],
    class: "default",
    costs: {
      food: 50,
      wood: 0,
      stone: 0,
      gold: 0,
      vizier: 0,
      oliveoil: 0,
      total: 50,
      popcap: 1,
      time: 20,
    },
    description:
      "Gathers Wood, Food, Stone, and Gold. Builds and repairs buildings and can repair siege engines and naval units.\n- Weak in combat",
    id: "villager-1",
  },
  {
    title: "Villager",
    age: 1,
    imgSrc: "/assets/pictures/unit_worker/villager-malians.png",
    civ: ["MAL"],
    class: "default",
    costs: {
      food: 50,
      wood: 0,
      stone: 0,
      gold: 0,
      vizier: 0,
      oliveoil: 0,
      total: 50,
      popcap: 1,
      time: 20,
    },
    description:
      "Gathers Wood, Food, Stone, and Gold. Builds and repairs buildings and can repair siege engines and naval units.\n- Weak in combat",
    id: "villager-1",
  },
  {
    title: "Villager",
    age: 1,
    imgSrc: "/assets/pictures/unit_worker/villager-china.png",
    civ: ["CHI", "ZXL"],
    class: "default",
    costs: {
      food: 50,
      wood: 0,
      stone: 0,
      gold: 0,
      vizier: 0,
      oliveoil: 0,
      total: 50,
      popcap: 1,
      time: 20,
    },
    description:
      "Gathers Wood, Food, Stone, and Gold. Builds and repairs buildings and can repair siege engines and naval units.\n- Weak in combat",
    id: "villager-1",
  },
  {
    title: "Villager",
    age: 1,
    imgSrc: "/assets/pictures/unit_worker/villager-abbasid.png",
    civ: ["ABB", "AYY"],
    class: "default",
    shorthand: "vil",
    costs: {
      food: 50,
      wood: 0,
      stone: 0,
      gold: 0,
      vizier: 0,
      oliveoil: 0,
      total: 50,
      popcap: 1,
      time: 20,
    },
    description:
      "Gathers Wood, Food, Stone, and Gold. Builds and repairs buildings and can repair siege engines and naval units.\n- Weak in combat",
    id: "villager-1",
  },
  {
    title: "Villager",
    age: 1,
    imgSrc: "/assets/pictures/unit_worker/villager-ottomans.png",
    civ: ["OTT"],
    class: "default",
    costs: {
      food: 50,
      wood: 0,
      stone: 0,
      gold: 0,
      vizier: 0,
      oliveoil: 0,
      total: 50,
      popcap: 1,
      time: 20,
    },
    description:
      "Gathers Wood, Food, Stone, and Gold. Builds and repairs buildings and can repair siege engines and naval units.\n- Weak in combat",
    id: "villager-1",
  },
  {
    title: "Villager",
    age: 1,
    imgSrc: "/assets/pictures/unit_worker/villager-mongols.png",
    civ: ["MON"],
    class: "default",
    costs: {
      food: 50,
      wood: 0,
      stone: 0,
      gold: 0,
      vizier: 0,
      oliveoil: 0,
      total: 50,
      popcap: 1,
      time: 20,
    },
    description:
      "Gathers Wood, Food, Stone, and Gold. Builds and repairs buildings and can repair siege engines and naval units.\n- Weak in combat",
    id: "villager-1",
  },
  {
    title: "Atabeg",
    age: 1,
    imgSrc: "/assets/pictures/unit_ayyubids/atabeg-1.png",
    civ: ["AYY"],
    class: "default",
    costs: {
      food: 0,
      wood: 0,
      stone: 0,
      gold: 0,
      vizier: 0,
      oliveoil: 0,
      total: 0,
      popcap: 1,
      time: 30,
    },
    description:
      "Can be garrisoned into any military production building to grant +20% health to newly trained units.",
    id: "atabeg-1",
  },
  {
    title: "Lodya Fishing Boat",
    age: 2,
    imgSrc: "/assets/pictures/unit_rus/lodya-fishing-boat.png",
    civ: ["RUS"],
    class: "default",
    costs: {
      food: 0,
      wood: 150,
      stone: 0,
      gold: 0,
      vizier: 0,
      oliveoil: 0,
      total: 150,
      popcap: 2,
      time: 38,
    },
    description:
      "Small boat that gathers Food from either Deep Water Fish or Shoreline Fish. Does not require a Dock to drop off gathered Food and gathers faster than a regular Fishing Boat.\n- No combat\nThe Lodya Fishing Boat can be converted to any other type of ship.",
    id: "lodya-fishing-boat-2",
  },
  {
    title: "Fishing Boat",
    age: 2,
    imgSrc: "/assets/pictures/unit_ship/fishing-boat.png",
    civ: [
      "ABB",
      "AYY",
      "BYZ",
      "CHI",
      "DEL",
      "DRA",
      "ENG",
      "FRE",
      "HRE",
      "JAP",
      "JDA",
      "MAL",
      "MON",
      "OTT",
      "ZXL",
    ],
    class: "default",
    costs: {
      food: 0,
      wood: 75,
      stone: 0,
      gold: 0,
      vizier: 0,
      oliveoil: 0,
      total: 75,
      popcap: 1,
      time: 25,
    },
    description:
      "Small boat that gathers Food from either Deep Water Fish or Shoreline Fish. Drops off gathered resources at the Dock.\n+ Can repair\n- No combat",
    id: "fishing-boat-2",
  },
  {
    title: "Trader",
    age: 1,
    imgSrc: "/assets/pictures/unit_worker/trader.png",
    civ: [
      "ABB",
      "AYY",
      "BYZ",
      "CHI",
      "DEL",
      "DRA",
      "ENG",
      "FRE",
      "HRE",
      "JAP",
      "JDA",
      "MAL",
      "MON",
      "OTT",
      "RUS",
      "ZXL",
    ],
    class: "default",
    costs: {
      food: 0,
      wood: 40,
      stone: 0,
      gold: 40,
      vizier: 0,
      oliveoil: 0,
      total: 80,
      popcap: 1,
      time: 30,
    },
    description:
      "Traders generate Gold when assigned to trade with a Trade Post or another player’s Market. The distance between the trade target and Market determines the amount of Gold. Once assigned to trade, the Trader makes repeated trips between its Home Market and the trade target. You can assign a new Home Market if you wish to.",
    id: "trader-1",
  },
  {
    title: "Imperial Official",
    age: 1,
    imgSrc: "/assets/pictures/unit_chinese/imperial-official.png",
    civ: ["CHI", "ZXL"],
    class: "default",
    costs: {
      food: 100,
      wood: 0,
      stone: 0,
      gold: 50,
      vizier: 0,
      oliveoil: 0,
      total: 150,
      popcap: 1,
      time: 20,
    },
    description:
      "Economic support unit with no combat capability. Automatically gathers Tax (Gold) from buildings.\n+ Can supervise buildings to improve their efficiency\n- Only a certain number of Officials can exist at a time",
    id: "imperial-official-1",
  },
  {
    title: "Trade Ship",
    age: 2,
    imgSrc: "/assets/pictures/unit_ship/trade-ship.png",
    civ: [
      "ABB",
      "AYY",
      "BYZ",
      "CHI",
      "DEL",
      "DRA",
      "ENG",
      "FRE",
      "HRE",
      "JAP",
      "JDA",
      "MAL",
      "MON",
      "OTT",
      "ZXL",
    ],
    class: "default",
    costs: {
      food: 0,
      wood: 100,
      stone: 0,
      gold: 100,
      vizier: 0,
      oliveoil: 0,
      total: 200,
      popcap: 2,
      time: 30,
    },
    description:
      "Trade Ships generate Gold and Wood when assigned to a trade route with a Coastal Trade Post or another player's Dock.\n- No combat",
    id: "trade-ship-2",
  },
  {
    title: "Lodya Trade Ship",
    age: 2,
    imgSrc: "/assets/pictures/unit_rus/lodya-trade-ship.png",
    civ: ["RUS"],
    class: "default",
    costs: {
      food: 0,
      wood: 100,
      stone: 0,
      gold: 100,
      vizier: 0,
      oliveoil: 0,
      total: 200,
      popcap: 2,
      time: 30,
    },
    description:
      "Trade Ships generate Gold and Wood when assigned to a trade route with a Coastal Trade Post or another player's Dock.\nThe Lodya can be converted to any other type of ship.",
    id: "lodya-trade-ship-2",
  },
];
