//Composables
import { civs } from "@/composables/builds/icons/civs.js";

//Exported methods
export const unitMilitary = [
  {
    title: "Scout",
    age: "1",
    imgSrc: "/assets/pictures/unit_cavalry/scout.png",
    civ: civs.exceptMany(["MAL"]),
    class: "military",
    shorthand: ["scout"],
  },
  {
    title: "Spearman",
    age: "1",
    imgSrc: "/assets/pictures/unit_infantry/spearman-1.png",
    civ: [
      "ENG",
      "FRE",
      "JDA",
      "RUS",
      "MON",
      "ABB",
      "AYY",
      "OTT",
      "CHI",
      "ZXL",
      "DEL",
      "HRE",
      "JAP",
    ],
    class: "military",
    shorthand: ["spear"],
  },
  {
    title: "Gilded Spearman",
    age: "1",
    imgSrc: "/assets/pictures/unit_dragon/gilded-spearman-1.png",
    civ: ["DRA"],
    class: "military",
    shorthand: ["spear"],
  },
  {
    title: "Limitanei",
    age: "1",
    imgSrc: "/assets/pictures/unit_byzantines/limitanei-1.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Camel Archer",
    age: "2",
    imgSrc: "/assets/pictures/unit_byzantines/camel-archer-2.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Camel Rider",
    age: "3",
    imgSrc: "/assets/pictures/unit_byzantines/camel-rider-3.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Ghulam",
    age: "3",
    imgSrc: "/assets/pictures/unit_byzantines/ghulam-3.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Desert Raider",
    age: "2",
    imgSrc: "/assets/pictures/unit_byzantines/desert-raider-2.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Arbalétrier",
    age: "3",
    imgSrc: "/assets/pictures/unit_byzantines/arbaletrier-3.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Grenadier",
    age: "4",
    imgSrc: "/assets/pictures/unit_byzantines/grenadier-4.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Horse Archer",
    age: "3",
    imgSrc: "/assets/pictures/unit_byzantines/horse-archer-3.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Javelin Thrower",
    age: "2",
    imgSrc: "/assets/pictures/unit_byzantines/javelin-thrower-2.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Keshik",
    age: "3",
    imgSrc: "/assets/pictures/unit_byzantines/keshik-2.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Landsknecht",
    age: "4",
    imgSrc: "/assets/pictures/unit_byzantines/landsknecht-3.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Longbowman",
    age: "2",
    imgSrc: "/assets/pictures/unit_byzantines/longbowman-2.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Mangudai",
    age: "2",
    imgSrc: "/assets/pictures/unit_byzantines/mangudai.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Musofadi Warrior",
    age: "2",
    imgSrc: "/assets/pictures/unit_byzantines/musofadi-warrior-2.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Royal Knight",
    age: "2",
    imgSrc: "/assets/pictures/unit_byzantines/royal-knight-2.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Sipahi",
    age: "2",
    imgSrc: "/assets/pictures/unit_byzantines/sipahi-2.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Streltsy",
    age: "3",
    imgSrc: "/assets/pictures/unit_byzantines/streltsy.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Tower Elephant",
    age: "3",
    imgSrc: "/assets/pictures/unit_byzantines/tower-elephant-3.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "War Elephant",
    age: "3",
    imgSrc: "/assets/pictures/unit_byzantines/war-elephant.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Zhuge Nu",
    age: "2",
    imgSrc: "/assets/pictures/unit_byzantines/zhuge-nu-2.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Samurai",
    age: "1",
    imgSrc: "/assets/pictures/unit_japanese/samurai-1.png",
    civ: ["JAP"],
    class: "military",
  },
  {
    title: "Yumi Ashigaru",
    age: "2",
    imgSrc: "/assets/pictures/unit_japanese/yumi-ashigaru-2.png",
    civ: ["JAP"],
    class: "military",
  },
  {
    title: "Archer",
    age: "2",
    imgSrc: "/assets/pictures/unit_infantry/archer-2.png",
    civ: civs.exceptMany(["ENG", "JAP", "DRA", "CHI", "ZXL"]),
    class: "military",
    shorthand: ["archer"],
  },
  {
    title: "Gilded Archer",
    age: "2",
    imgSrc: "/assets/pictures/unit_dragon/gilded-archer-2.png",
    civ: ["DRA"],
    class: "military",
    shorthand: ["archer"],
  },
  {
    title: "Shinobi",
    age: "2",
    imgSrc: "/assets/pictures/unit_japanese/shinobi-2.png",
    civ: ["JAP"],
    class: "military",
  },
  {
    title: "Imperial Guard",
    age: "2",
    imgSrc: "/assets/pictures/unit_zhuxi/imperial-guard-1.png",
    civ: ["ZXL"],
    class: "military",
  },
  {
    title: "Onna-Bugeisha",
    age: "2",
    imgSrc: "/assets/pictures/unit_japanese/onna-bugeisha-2.png",
    civ: ["JAP"],
    class: "military",
  },
  {
    title: "Yumi Bannerman",
    age: "2",
    imgSrc: "/assets/pictures/unit_japanese/yumi-bannerman-2.png",
    civ: ["JAP"],
    class: "military",
  },
  {
    title: "Katana Bannerman",
    age: "2",
    imgSrc: "/assets/pictures/unit_japanese/katana-bannerman-2.png",
    civ: ["JAP"],
    class: "military",
  },
  {
    title: "Uma Bannerman",
    age: "2",
    imgSrc: "/assets/pictures/unit_japanese/uma-bannerman-2.png",
    civ: ["JAP"],
    class: "military",
  },
  {
    title: "Onna-Musha",
    age: "3",
    imgSrc: "/assets/pictures/unit_japanese/onna-musha-3.png",
    civ: ["JAP"],
    class: "military",
  },
  {
    title: "Mounted Samurai",
    age: "3",
    imgSrc: "/assets/pictures/unit_japanese/mounted-samurai-3.png",
    civ: ["JAP"],
    class: "military",
  },
  {
    title: "Crossbowman",
    age: "3",
    imgSrc: "/assets/pictures/unit_infantry/crossbowman-3.png",
    civ: civs.exceptMany(["FRE", "MAL", "JAP", "DRA"]),
    class: "military",
    shorthand: ["xbow"],
  },
  {
    title: "Gilded Crossbowman",
    age: "3",
    imgSrc: "/assets/pictures/unit_dragon/gilded-crossbowman-3.png",
    civ: ["DRA"],
    class: "military",
    shorthand: ["xbow"],
  },
  {
    title: "Handcannoneer",
    age: "4",
    imgSrc: "/assets/pictures/unit_infantry/handcannoneer-4.png",
    civ: civs.exceptMany(["OTT", "MAL", "DRA", "JAP"]),
    class: "military",
  },
  {
    title: "Handcannon Ashigaru",
    age: "4",
    imgSrc: "/assets/pictures/unit_infantry/handcannoneer-4.png",
    civ: ["JAP"],
    class: "military",
  },
  {
    title: "Dragon Handcannoneer",
    age: "4",
    imgSrc: "/assets/pictures/unit_dragon/dragon-handcannoneer-4.png",
    civ: ["DRA"],
    class: "military",
  },
  {
    title: "Ozutsu",
    age: "4",
    imgSrc: "/assets/pictures/unit_japanese/ozutsu-4.png",
    civ: ["JAP"],
    class: "military",
  },
  {
    title: "Man-at-Arms",
    age: "3",
    imgSrc: "/assets/pictures/unit_infantry/man-at-arms-1.png",
    civ: ["ENG", "FRE", "JDA", "RUS", "MON", "OTT", "DEL", "HRE"],
    class: "military",
    shorthand: ["maa"],
  },
  {
    title: "Gilded Man-at-Arms",
    age: "2",
    imgSrc: "/assets/pictures/unit_dragon/gilded-man-at-arms-2.png",
    civ: ["DRA"],
    class: "military",
    shorthand: ["maa"],
  },
  {
    title: "Jeanne's Champion",
    age: "3",
    imgSrc: "/assets/pictures/unit_jeanne/jeannes-champion-3.png",
    civ: ["JDA"],
    class: "military",
  },
  {
    title: "Ghulam",
    age: "3",
    imgSrc: "/assets/pictures/unit_abbasid/ghulam-3.png",
    civ: ["ABB", "AYY"],
    class: "military",
  },
  {
    title: "Varangian Guard",
    age: "3",
    imgSrc: "/assets/pictures/unit_byzantines/varangian-guard-3.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Horseman",
    age: "2",
    imgSrc: "/assets/pictures/unit_cavalry/horseman-1.png",
    civ: [
      "ENG",
      "FRE",
      "JDA",
      "RUS",
      "MON",
      "OTT",
      "CHI",
      "ZXL",
      "HRE",
      "BYZ",
      "JAP",
      "ABB",
      "AYY",
    ],
    class: "military",
  },
  {
    title: "Gilded Horseman",
    age: "2",
    imgSrc: "/assets/pictures/unit_dragon/gilded-horseman-2.png",
    civ: ["DRA"],
    class: "military",
  },
  {
    title: "Ghazi Raider",
    age: "2",
    imgSrc: "/assets/pictures/unit_delhi/ghazi-raider-2.png",
    civ: ["DEL"],
    class: "military",
  },
  {
    title: "Knight",
    age: "3",
    imgSrc: "/assets/pictures/unit_cavalry/knight-2.png",
    civ: ["ENG", "RUS", "HRE"],
    class: "military",
  },
  {
    title: "Gilded Knight",
    age: "3",
    imgSrc: "/assets/pictures/unit_dragon/gilded-knight-3.png",
    civ: ["DRA"],
    class: "military",
  },
  {
    title: "Cataphract",
    age: "3",
    imgSrc: "/assets/pictures/unit_byzantines/cataphract-3.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Lancer",
    age: "3",
    imgSrc: "/assets/pictures/unit_cavalry/lancer-3.png",
    civ: ["ABB", "AYY", "OTT", "CHI", "ZXL", "DEL"],
    class: "military",
  },
  {
    title: "Bedouin Swordsman",
    age: "1",
    imgSrc: "/assets/pictures/unit_ayyubids/bedouin-swordsman-1.png",
    civ: ["AYY"],
    class: "military",
  },
  {
    title: "Bedouin Skirmisher",
    age: "2",
    imgSrc: "/assets/pictures/unit_ayyubids/bedouin-skirmisher-2.png",
    civ: ["AYY"],
    class: "military",
  },
  {
    title: "Desert Raider",
    age: "2",
    imgSrc: "/assets/pictures/unit_ayyubids/desert-raider-2.png",
    civ: ["AYY"],
    class: "military",
  },
  {
    title: "Camel Lancer",
    age: "3",
    imgSrc: "/assets/pictures/unit_ayyubids/camel-lancer-3.png",
    civ: ["AYY"],
    class: "military",
  },
  {
    title: "Camel Rider",
    age: "3",
    imgSrc: "/assets/pictures/unit_abbasid/camel-rider-3.png",
    civ: ["ABB"],
    class: "military",
  },
  {
    title: "Camel Archer",
    age: "2",
    imgSrc: "/assets/pictures/unit_abbasid/camel-archer-2.png",
    civ: ["ABB"],
    class: "military",
  },
  {
    title: "Zhuge Nu",
    age: "2",
    imgSrc: "/assets/pictures/unit_chinese/zhuge-nu-2.png",
    civ: ["CHI", "ZXL"],
    class: "military",
  },
  {
    title: "Palace Guard",
    age: "3",
    imgSrc: "/assets/pictures/unit_chinese/palace-guard-3.png",
    civ: ["CHI", "ZXL"],
    class: "military",
  },
  {
    title: "Nest of Bees",
    age: "3",
    imgSrc: "/assets/pictures/unit_chinese/nest-of-bees.png",
    civ: ["CHI", "ZXL"],
    class: "military",
  },
  {
    title: "Fire Lancer",
    age: "3",
    imgSrc: "/assets/pictures/unit_chinese/fire-lancer-3.png",
    civ: ["CHI"],
    class: "military",
  },
  {
    title: "Yuan Raider",
    age: "4",
    imgSrc: "/assets/pictures/unit_zhuxi/yuan-raider-4.png",
    civ: ["CHI", "ZXL"],
    class: "military",
  },
  {
    title: "Grenadier",
    age: "4",
    imgSrc: "/assets/pictures/unit_chinese/grenadier-4.png",
    civ: ["CHI", "ZXL"],
    class: "military",
  },
  {
    title: "Tower Elephant",
    age: "3",
    imgSrc: "/assets/pictures/unit_delhi/tower-elephant-3.png",
    civ: ["DEL"],
    class: "military",
  },
  {
    title: "Sultan's Elite Tower Elephant",
    age: "4",
    imgSrc: "/assets/pictures/unit_delhi/sultans-elite-tower-elephant-4.png",
    civ: ["DEL"],
    class: "military",
  },
  {
    title: "War Elephant",
    age: "3",
    imgSrc: "/assets/pictures/unit_delhi/war-elephant.png",
    civ: ["DEL"],
    class: "military",
  },
  {
    title: "Longbowman",
    age: "2",
    imgSrc: "/assets/pictures/unit_english/longbowman-2.png",
    civ: ["ENG"],
    class: "military",
  },
  {
    title: "King",
    age: "2",
    imgSrc: "/assets/pictures/unit_english/king-2.png",
    civ: ["ENG"],
    class: "military",
  },
  {
    title: "Wynguard Ranger",
    age: "4",
    imgSrc: "/assets/pictures/unit_english/wynguard-ranger-4.png",
    civ: ["ENG"],
    class: "military",
  },
  {
    title: "Wynguard Footmen",
    age: "4",
    imgSrc: "/assets/pictures/unit_english/wynguard-footmen-1.png",
    civ: ["ENG"],
    class: "military",
  },
  {
    title: "Wynguard Army",
    age: "4",
    imgSrc: "/assets/pictures/unit_english/wynguard-army-1.png",
    civ: ["ENG"],
    class: "military",
  },
  {
    title: "Wynguard Raiders",
    age: "4",
    imgSrc: "/assets/pictures/unit_english/wynguard-raiders-1.png",
    civ: ["ENG"],
    class: "military",
  },
  {
    title: "Royal Knight",
    age: "2",
    imgSrc: "/assets/pictures/unit_french/royal-knight-2.png",
    civ: ["FRE", "JDA"],
    class: "military",
  },
  {
    title: "Jeanne's Rider",
    age: "3",
    imgSrc: "/assets/pictures/unit_jeanne/jeannes-rider-3.png",
    civ: ["JDA"],
    class: "military",
  },
  {
    title: "Arbalétrier",
    age: "3",
    imgSrc: "/assets/pictures/unit_french/arbaletrier-3.png",
    civ: ["FRE", "JDA"],
    class: "military",
  },
  {
    title: "Galleass",
    age: "3",
    imgSrc: "/assets/pictures/unit_french/galleass.png",
    civ: ["FRE", "JDA"],
    class: "military",
  },
  {
    title: "Cannon",
    age: "4",
    imgSrc: "/assets/pictures/unit_french/cannon-4.png",
    civ: ["FRE", "JDA"],
    class: "military",
  },
  {
    title: "Royal Cannon",
    age: "4",
    imgSrc: "/assets/pictures/unit_french/royal-cannon-4.png",
    civ: ["FRE", "JDA"],
    class: "military",
  },
  {
    title: "Royal Culverin",
    age: "4",
    imgSrc: "/assets/pictures/unit_french/royal-culverin-4.png",
    civ: ["FRE", "JDA"],
    class: "military",
  },
  {
    title: "Royal Ribauldequin",
    age: "4",
    imgSrc: "/assets/pictures/unit_french/royal-ribauldequin-4.png",
    civ: ["FRE", "JDA"],
    class: "military",
  },
  {
    title: "Landsknecht",
    age: "4",
    imgSrc: "/assets/pictures/unit_hre/landsknecht-3.png",
    civ: ["HRE"],
    class: "military",
  },
  {
    title: "Gilded Landsknecht",
    age: "4",
    imgSrc: "/assets/pictures/unit_dragon/gilded-landsknecht-3.png",
    civ: ["DRA"],
    class: "military",
  },
  {
    title: "Donso",
    age: "1",
    imgSrc: "/assets/pictures/unit_malians/donso-1.png",
    civ: ["MAL"],
    class: "military",
  },
  {
    title: "Musofadi Warrior",
    age: "2",
    imgSrc: "/assets/pictures/unit_malians/musofadi-warrior-2.png",
    civ: ["MAL"],
    class: "military",
  },
  {
    title: "Javelin Thrower",
    age: "2",
    imgSrc: "/assets/pictures/unit_malians/javelin-thrower-2.png",
    civ: ["MAL"],
    class: "military",
  },
  {
    title: "Warrior Scout",
    age: "1",
    imgSrc: "/assets/pictures/unit_malians/warrior-scout-2.png",
    civ: ["MAL"],
    class: "military",
  },
  {
    title: "Sofa",
    age: "2",
    imgSrc: "/assets/pictures/unit_malians/sofa-2.png",
    civ: ["MAL"],
    class: "military",
  },
  {
    title: "Musofadi Gunner",
    age: "4",
    imgSrc: "/assets/pictures/unit_malians/musofadi-gunner-4.png",
    civ: ["MAL"],
    class: "military",
  },
  {
    title: "Khan",
    age: "1",
    imgSrc: "/assets/pictures/unit_mongols/khan-1.png",
    civ: ["MON"],
    class: "military",
  },
  {
    title: "Mangudai",
    age: "2",
    imgSrc: "/assets/pictures/unit_mongols/mangudai.png",
    civ: ["MON"],
    class: "military",
  },
  {
    title: "Keshik",
    age: "3",
    imgSrc: "/assets/pictures/unit_mongols/keshik-2.png",
    civ: ["MON"],
    class: "military",
  },
  {
    title: "Traction Trebuchet",
    age: "2",
    imgSrc: "/assets/pictures/unit_mongols/traction-trebuchet.png",
    civ: ["MON"],
    class: "military",
  },
  {
    title: "Huihui Pao",
    age: "4",
    imgSrc: "/assets/pictures/unit_mongols/huihui-pao-1.png",
    civ: ["MON"],
    class: "military",
  },
  {
    title: "Sipahi",
    age: "2",
    imgSrc: "/assets/pictures/unit_ottomans/sipahi-2.png",
    civ: ["OTT"],
    class: "military",
  },
  {
    title: "Mehter",
    age: "2",
    imgSrc: "/assets/pictures/unit_ottomans/mehter-2.png",
    civ: ["OTT"],
    class: "military",
  },
  {
    title: "Janissary",
    age: "3",
    imgSrc: "/assets/pictures/unit_ottomans/janissary-3.png",
    civ: ["OTT"],
    class: "military",
  },
  {
    title: "Great Bombard",
    age: "4",
    imgSrc: "/assets/pictures/unit_ottomans/great-bombard-4.png",
    civ: ["OTT"],
    class: "military",
  },
  {
    title: "Grand Galley",
    age: "4",
    imgSrc: "/assets/pictures/unit_ottomans/grand-galley-4.png",
    civ: ["OTT"],
    class: "military",
  },
  {
    title: "Dromon",
    age: "2",
    imgSrc: "/assets/pictures/unit_byzantines/dromon-2.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Transport Ship",
    age: "1",
    imgSrc: "/assets/pictures/unit_ship/transport-ship.png",
    civ: civs.exceptMany(["RUS"]),
    class: "military",
  },
  {
    title: "Lodya Transport Ship",
    age: "1",
    imgSrc: "/assets/pictures/unit_rus/lodya-transport-ship.png",
    civ: ["RUS"],
    class: "military",
  },
  {
    title: "Lodya Galley",
    age: "2",
    imgSrc: "/assets/pictures/unit_rus/lodya-galley-3.png",
    civ: ["RUS"],
    class: "military",
  },
  {
    title: "Lodya Demolition Ship",
    age: "2",
    imgSrc: "/assets/pictures/unit_rus/lodya-demolition-ship.png",
    civ: ["RUS"],
    class: "military",
  },
  {
    title: "Lodya Attack Ship",
    age: "2",
    imgSrc: "/assets/pictures/unit_rus/lodya-attack-ship.png",
    civ: ["RUS"],
    class: "military",
  },
  {
    title: "Warrior Monk",
    age: "3",
    imgSrc: "/assets/pictures/unit_rus/warrior-monk.png",
    civ: ["RUS"],
    class: "military",
    shorthand: ["monk"],
  },
  {
    title: "Horse Archer",
    age: "3",
    imgSrc: "/assets/pictures/unit_rus/horse-archer-3.png",
    civ: ["RUS"],
    class: "military",
  },
  {
    title: "Streltsy",
    age: "3",
    imgSrc: "/assets/pictures/unit_rus/streltsy.png",
    civ: ["RUS"],
    class: "military",
  },
  {
    title: "Militia",
    age: "2",
    imgSrc: "/assets/pictures/unit_rus/militia-2.png",
    civ: ["RUS"],
    class: "military",
  },
  {
    title: "Siege Tower",
    age: "2",
    imgSrc: "/assets/pictures/unit_siege/siege-tower.png",
    civ: civs,
    class: "military",
  },
  {
    title: "Battering Ram",
    age: "2",
    imgSrc: "/assets/pictures/unit_siege/battering-ram.png",
    civ: civs.exceptMany("BYZ"),
    class: "military",
  },
  {
    title: "Cheirosiphon",
    age: "2",
    imgSrc: "/assets/pictures/unit_byzantines/cheirosiphon-3.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Tower of the Sultan",
    age: "3",
    imgSrc: "/assets/pictures/unit_byzantines/tower-of-the-sultan-3.png",
    civ: ["BYZ"],
    class: "military",
  },
  {
    title: "Springald",
    age: "3",
    imgSrc: "/assets/pictures/unit_siege/springald.png",
    civ: civs,
    class: "military",
  },
  {
    title: "Mangonel",
    age: "3",
    imgSrc: "/assets/pictures/unit_siege/mangonel-3.png",
    civ: civs.exceptMany(["CHI", "ZXL", "AYY"]),
    class: "military",
  },
  {
    title: "Manjaniq",
    age: "3",
    imgSrc: "/assets/pictures/unit_ayyubids/manjaniq-3.png",
    civ: ["AYY"],
    class: "military",
  },
  {
    title: "Tower of the Sultan",
    age: "3",
    imgSrc: "/assets/pictures/unit_ayyubids/tower-of-the-sultan-3.png",
    civ: ["AYY"],
    class: "military",
  },
  {
    title: "Counterweight Trebuchet",
    age: "3",
    imgSrc: "/assets/pictures/unit_siege/trebuchet.png",
    civ: civs.exceptMany(["MON"]),
    class: "military",
  },
  {
    title: "Bombard",
    age: "3",
    imgSrc: "/assets/pictures/unit_siege/bombard.png",
    civ: [
      "ENG",
      "RUS",
      "MAL",
      "MON",
      "ABB",
      "AYY",
      "CHI",
      "ZXL",
      "DEL",
      "HRE",
      "DRA",
      "BYZ",
      "JAP",
    ],
    class: "military",
  },
  {
    title: "Ribauldequin",
    age: "4",
    imgSrc: "/assets/pictures/unit_siege/ribauldequin-4.png",
    civ: ["ENG", "FRE", "JDA", "OTT", "JAP"],
    class: "military",
  },
  {
    title: "Culverin",
    age: "4",
    imgSrc: "/assets/pictures/unit_siege/culverin-4.png",
    civ: ["ABB", "AYY", "HRE", "DRA", "FRE", "JDA", "MAL"],
    class: "military",
  },
  {
    title: "Dhow",
    age: "2",
    imgSrc: "/assets/pictures/unit_ship/dhow.png",
    civ: ["ABB", "AYY", "DEL", "OTT"],
    class: "military",
  },
  {
    title: "Galley",
    age: "2",
    imgSrc: "/assets/pictures/unit_ship/dhow.png",
    civ: ["ENG", "HRE", "DRA", "FRE", "JDA", "BYZ"],
    class: "military",
  },
  {
    title: "Junk",
    age: "2",
    imgSrc: "/assets/pictures/unit_ship/dhow.png",
    civ: ["CHI", "ZXL", "JAP"],
    class: "military",
  },
  {
    title: "Light Junk",
    age: "2",
    imgSrc: "/assets/pictures/unit_ship/dhow.png",
    civ: ["MON"],
    class: "military",
  },
  {
    title: "Hunting Canoe",
    age: "2",
    imgSrc: "/assets/pictures/unit_ship/dhow.png",
    civ: ["MAL"],
    class: "military",
  },
  {
    title: "Baghlah",
    age: "2",
    imgSrc: "/assets/pictures/unit_ship/baghlah.png",
    civ: ["ABB", "AYY", "DEL"],
    class: "military",
  },
  {
    title: "Hulk",
    age: "2",
    imgSrc: "/assets/pictures/unit_ship/baghlah.png",
    civ: ["ENG", "HRE", "DRA", "OTT"],
    class: "military",
  },
  {
    title: "War Cog",
    age: "2",
    imgSrc: "/assets/pictures/unit_french/war-cog.png",
    civ: ["FRE", "JDA"],
    class: "military",
  },
  {
    title: "War Junk",
    age: "2",
    imgSrc: "/assets/pictures/unit_ship/baghlah.png",
    civ: ["CHI", "ZXL", "MON", "JAP"],
    class: "military",
  },
  {
    title: "Atakebune",
    age: "4",
    imgSrc: "/assets/pictures/unit_japanese/atakebune-4.png",
    civ: ["JAP"],
    class: "military",
  },
  {
    title: "War Canoe",
    age: "2",
    imgSrc: "/assets/pictures/unit_ship/baghlah.png",
    civ: ["MAL"],
    class: "military",
  },
  {
    title: "Explosive Dhow",
    age: "2",
    imgSrc: "/assets/pictures/unit_ship/explosive-dhow.png",
    civ: ["ABB", "AYY", "DEL"],
    class: "military",
  },
  {
    title: "Demolition Ship",
    age: "2",
    imgSrc: "/assets/pictures/unit_ship/explosive-dhow.png",
    civ: ["ENG", "FRE", "JDA", "HRE", "DRA", "MAL", "OTT", "BYZ"],
    class: "military",
  },
  {
    title: "Explosive Junk",
    age: "2",
    imgSrc: "/assets/pictures/unit_ship/explosive-dhow.png",
    civ: ["CHI", "ZXL", "MON", "JAP"],
    class: "military",
  },
  {
    title: "Xebec",
    age: "4",
    imgSrc: "/assets/pictures/unit_ship/xebec.png",
    civ: ["ABB", "AYY", "DEL"],
    class: "military",
  },
  {
    title: "Carrack",
    age: "4",
    imgSrc: "/assets/pictures/unit_ship/xebec.png",
    civ: ["ENG", "FRE", "JDA", "HRE", "DRA", "OTT", "BYZ"],
    class: "military",
  },
  {
    title: "Baochuan",
    age: "4",
    imgSrc: "/assets/pictures/unit_ship/xebec.png",
    civ: ["CHI", "ZXL", "MON"],
    class: "military",
  },
];
