import { ref } from "vue";

export default function useIconService(civArg) {
  const civ = ref(civArg);

  const getIcons = (category) => {
    var allIcons = [];

    switch (category) {
      case "general":
        allIcons = general;
        break;
      case "landmark":
        allIcons = landmark;
        break;
      case "tech_eco":
        allIcons = tech_eco;
        break;
      case "tech_military":
        allIcons = tech_military;
        break;
      case "building_religious":
        allIcons = building_religious;
        break;
      case "building_eco":
        allIcons = building_eco;
        break;
      case "building_tech":
        allIcons = building_tech;
        break;
      case "resource":
        allIcons = resource;
        break;
      case "building_military":
        allIcons = building_military;
        break;
      case "unit_religious":
        allIcons = unit_religious;
        break;
      case "unit_military":
        allIcons = unit_military;
        break;
      case "unit_eco":
        allIcons = unit_eco;
        break;
      default:
        allIcons = general
          .concat(landmark)
          .concat(tech_eco)
          .concat(tech_military)
          .concat(building_religious)
          .concat(building_eco)
          .concat(building_tech)
          .concat(building_military)
          .concat(unit_religious)
          .concat(unit_military)
          .concat(unit_eco);
        break;
    }

    if (civ.value) {
      return allIcons.filter((icon) => icon.civ.includes(civ.value));
    } else {
      return allIcons;
    }
  };

  const general = [
    {
      title: "Dark Age",
      age: "1",
      imgSrc: "/assets/pictures/age/age_1.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Feudal Age",
      age: "2",
      imgSrc: "/assets/pictures/age/age_2.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Castle Age",
      age: "3",
      imgSrc: "/assets/pictures/age/age_3.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Imperial Age",
      age: "4",
      imgSrc: "/assets/pictures/age/age_4.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Unknown Age",
      age: "1",
      imgSrc: "/assets/pictures/age/age_unknown.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Golde Age Tier 1",
      age: "1",
      imgSrc: "/assets/pictures/age/goldenagetier1.png",
      civ: [
        "ABB",
      ],
    },
    {
      title: "Golde Age Tier 2",
      age: "4",
      imgSrc: "/assets/pictures/age/goldenagetier2.png",
      civ: [
        "ABB",
      ],
    },
    {
      title: "Golde Age Tier 3",
      age: "1",
      imgSrc: "/assets/pictures/age/goldenagetier3.png",
      civ: [
        "ABB",
      ],
    },
  ];

  const resource = [
    {
      title: "Food",
      age: "1",
      imgSrc: "/assets/pictures/resource/resource_food.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Wood",
      age: "1",
      imgSrc: "/assets/pictures/resource/resource_wood.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Gold",
      age: "1",
      imgSrc: "/assets/pictures/resource/resource_gold.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Stone",
      age: "1",
      imgSrc: "/assets/pictures/resource/resource_stone.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Sheep",
      age: "1",
      imgSrc: "/assets/pictures/resource/sheep.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Deer",
      age: "1",
      imgSrc: "/assets/pictures/resource/deer.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Berries",
      age: "1",
      imgSrc: "/assets/pictures/resource/berrybush.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Boar",
      age: "1",
      imgSrc: "/assets/pictures/resource/boar.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Build or Repair",
      age: "1",
      imgSrc: "/assets/pictures/resource/repair.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Rally",
      age: "1",
      imgSrc: "/assets/pictures/resource/rally.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Fish",
      age: "1",
      imgSrc: "/assets/pictures/resource/fish.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Straggler Tree",
      age: "1",
      imgSrc: "/assets/pictures/resource/gaiatreeprototypetree.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    ,
    {
      title: "Wolf",
      age: "1",
      imgSrc: "/assets/pictures/resource/wolf.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
  ];

  const landmark = [
    {
      title: "Abbey of Kings",
      age: "1",
      imgSrc: "/assets/pictures/landmark_english/abbey-of-kings.png",
      civ: ["ENG"],
    },
    {
      title: "Council Hall",
      age: "1",
      imgSrc: "/assets/pictures/landmark_english/council-hall.png",
      civ: ["ENG"],
    },
    {
      title: "King's Palace",
      age: "2",
      imgSrc: "/assets/pictures/landmark_english/kings-palace.png",
      civ: ["ENG"],
    },
    {
      title: "The White Tower",
      age: "2",
      imgSrc: "/assets/pictures/landmark_english/the-white-tower.png",
      civ: ["ENG"],
    },
    {
      title: "Wynguard Palace",
      age: "3",
      imgSrc: "/assets/pictures/landmark_english/wynguard-palace.png",
      civ: ["ENG"],
    },
    {
      title: "Berkshire Palace",
      age: "3",
      imgSrc: "/assets/pictures/landmark_english/berkshire-palace.png",
      civ: ["ENG"],
    },
    {
      title: "Cathedral of St. Thomas",
      age: "4",
      imgSrc: "/assets/pictures/landmark_english/cathedral-of-st-thomas.png",
      civ: ["ENG"],
    },
    {
      title: "Chamber of Commerce",
      age: "1",
      imgSrc: "/assets/pictures/landmark_french/chamber-of-commerce.png",
      civ: ["FRE"],
    },
    {
      title: "School of Cavalry",
      age: "1",
      imgSrc: "/assets/pictures/landmark_french/school-of-cavalry.png",
      civ: ["FRE"],
    },
    {
      title: "Guild Hall",
      age: "2",
      imgSrc: "/assets/pictures/landmark_french/guild-hall.png",
      civ: ["FRE"],
    },
    {
      title: "Royal Institute",
      age: "2",
      imgSrc: "/assets/pictures/landmark_french/royal-institute.png",
      civ: ["FRE"],
    },
    {
      title: "College of Artillery",
      age: "3",
      imgSrc: "/assets/pictures/landmark_french/college-of-artillery.png",
      civ: ["FRE"],
    },
    {
      title: "Red Palace",
      age: "3",
      imgSrc: "/assets/pictures/landmark_french/red-palace.png",
      civ: ["FRE"],
    },
    {
      title: "Notre Dame",
      age: "4",
      imgSrc: "/assets/pictures/landmark_french/notre-dame.png",
      civ: ["FRE"],
    },
    {
      title: "Aachen Chapel",
      age: "1",
      imgSrc: "/assets/pictures/landmark_hre/aachen-chapel.png",
      civ: ["HRE"],
    },
    {
      title: "Meinwerk Palace",
      age: "1",
      imgSrc: "/assets/pictures/landmark_hre/meinwerk-palace.png",
      civ: ["HRE"],
    },
    {
      title: "Burgrave Palace",
      age: "2",
      imgSrc: "/assets/pictures/landmark_hre/burgrave-palace.png",
      civ: ["HRE"],
    },
    {
      title: "Regnitz Cathedral",
      age: "2",
      imgSrc: "/assets/pictures/landmark_hre/regnitz-cathedral.png",
      civ: ["HRE"],
    },
    {
      title: "Elzbach Palace",
      age: "3",
      imgSrc: "/assets/pictures/landmark_hre/elzbach-palace.png",
      civ: ["HRE"],
    },
    {
      title: "Palace of Swabia",
      age: "3",
      imgSrc: "/assets/pictures/landmark_hre/palace-of-swabia.png",
      civ: ["HRE"],
    },
    {
      title: "Great Palace of Flensburg",
      age: "4",
      imgSrc: "/assets/pictures/landmark_hre/great-palace-of-flensburg.png",
      civ: ["HRE"],
    },
    {
      title: "Saharan Trade Network",
      age: "1",
      imgSrc: "/assets/pictures/landmark_malians/saharan-trade-network-1.png",
      civ: ["MAL"],
    },
    {
      title: "Mansa Quarry",
      age: "1",
      imgSrc: "/assets/pictures/landmark_malians/mansa-quarry-2.png",
      civ: ["MAL"],
    },
    {
      title: "Grand Fulani Corral",
      age: "2",
      imgSrc: "/assets/pictures/landmark_malians/grand-fulani-corral-2.png",
      civ: ["MAL"],
    },
    {
      title: "Farimba Garrison",
      age: "2",
      imgSrc: "/assets/pictures/landmark_malians/farimba-garrison-2.png",
      civ: ["MAL"],
    },
    {
      title: "Fort of the Huntress",
      age: "3",
      imgSrc: "/assets/pictures/landmark_malians/fort-of-the-huntress-3.png",
      civ: ["MAL"],
    },
    {
      title: "Griot Bara",
      age: "3",
      imgSrc: "/assets/pictures/landmark_malians/griot-bara-3.png",
      civ: ["MAL"],
    },
    {
      title: "Great Mosque",
      age: "4",
      imgSrc: "/assets/pictures/landmark_malians/great-mosque-4.png",
      civ: ["MAL"],
    },
    {
      title: "Deer Stones",
      age: "1",
      imgSrc: "/assets/pictures/landmark_mongols/deer-stones.png",
      civ: ["MON"],
    },
    {
      title: "The Silver Tree",
      age: "1",
      imgSrc: "/assets/pictures/landmark_mongols/the-silver-tree.png",
      civ: ["MON"],
    },
    {
      title: "Kurultai",
      age: "2",
      imgSrc: "/assets/pictures/landmark_mongols/kurultai.png",
      civ: ["MON"],
    },
    {
      title: "Steppe Redoubt",
      age: "2",
      imgSrc: "/assets/pictures/landmark_mongols/steppe-redoubt.png",
      civ: ["MON"],
    },
    {
      title: "Khaganate Palace",
      age: "3",
      imgSrc: "/assets/pictures/landmark_mongols/khaganate-palace.png",
      civ: ["MON"],
    },
    {
      title: "The White Stupa",
      age: "3",
      imgSrc: "/assets/pictures/landmark_mongols/the-white-stupa.png",
      civ: ["MON"],
    },
    {
      title: "Monument of the Great Khan",
      age: "4",
      imgSrc:
        "/assets/pictures/landmark_mongols/monument-of-the-great-khan.png",
      civ: ["MON"],
    },
    {
      title: "Twin Minaret Medrese",
      age: "1",
      imgSrc: "/assets/pictures/landmark_ottomans/twin-minaret-medrese-1.png",
      civ: ["OTT"],
    },
    {
      title: "Sultanhani Trade Network",
      age: "1",
      imgSrc:
        "/assets/pictures/landmark_ottomans/sultanhani-trade-network-1.png",
      civ: ["OTT"],
    },
    {
      title: "Istanbul Imperial Palace",
      age: "2",
      imgSrc:
        "/assets/pictures/landmark_ottomans/istanbul-imperial-palace-2.png",
      civ: ["OTT"],
    },
    {
      title: "Mehmed Imperial Armory",
      age: "2",
      imgSrc: "/assets/pictures/landmark_ottomans/mehmed-imperial-armory-2.png",
      civ: ["OTT"],
    },
    {
      title: "Istanbul Observatory",
      age: "3",
      imgSrc: "/assets/pictures/landmark_ottomans/istanbul-observatory-3.png",
      civ: ["OTT"],
    },
    {
      title: "Sea Gate Castle",
      age: "3",
      imgSrc: "/assets/pictures/landmark_ottomans/sea-gate-castle-3.png",
      civ: ["OTT"],
    },
    {
      title: "Azure Mosque",
      age: "4",
      imgSrc: "/assets/pictures/landmark_ottomans/azure-mosque-4.png",
      civ: ["OTT"],
    },
    {
      title: "Kremlin",
      age: "1",
      imgSrc: "/assets/pictures/landmark_rus/kremlin.png",
      civ: ["RUS"],
    },
    {
      title: "The Golden Gate",
      age: "1",
      imgSrc: "/assets/pictures/landmark_rus/the-golden-gate.png",
      civ: ["RUS"],
    },
    {
      title: "Abbey of the Trinity",
      age: "2",
      imgSrc: "/assets/pictures/landmark_rus/abbey-of-the-trinity.png",
      civ: ["RUS"],
    },
    {
      title: "High Trade House",
      age: "2",
      imgSrc: "/assets/pictures/landmark_rus/high-trade-house.png",
      civ: ["RUS"],
    },
    {
      title: "High Armory",
      age: "3",
      imgSrc: "/assets/pictures/landmark_rus/high-armory.png",
      civ: ["RUS"],
    },
    {
      title: "Spasskaya Tower",
      age: "3",
      imgSrc: "/assets/pictures/landmark_rus/spasskaya-tower.png",
      civ: ["RUS"],
    },
    {
      title: "Cathedral of the Tsar",
      age: "4",
      imgSrc: "/assets/pictures/landmark_rus/cathedral-of-the-tsar.png",
      civ: ["RUS"],
    },
    {
      title: "House of Wisdom",
      age: "1",
      imgSrc: "/assets/pictures/landmark_abbasid/house-of-wisdom.png",
      civ: ["ABB"],
    },
    {
      title: "Culture Wing",
      age: "1",
      imgSrc: "/assets/pictures/landmark_abbasid/culture-wing.png",
      civ: ["ABB"],
    },
    {
      title: "Economic Wing",
      age: "1",
      imgSrc: "/assets/pictures/landmark_abbasid/economic-wing.png",
      civ: ["ABB"],
    },
    {
      title: "Military Wing",
      age: "1",
      imgSrc: "/assets/pictures/landmark_abbasid/military-wing.png",
      civ: ["ABB"],
    },
    {
      title: "Trade Wing",
      age: "1",
      imgSrc: "/assets/pictures/landmark_abbasid/trade-wing.png",
      civ: ["ABB"],
    },
    {
      title: "Imperial Academy",
      age: "1",
      imgSrc: "/assets/pictures/landmark_chinese/imperial-academy.png",
      civ: ["CHI"],
    },
    {
      title: "Barbican of the Sun",
      age: "1",
      imgSrc: "/assets/pictures/landmark_chinese/barbican-of-the-sun.png",
      civ: ["CHI"],
    },
    {
      title: "Astronomical Clocktower",
      age: "2",
      imgSrc: "/assets/pictures/landmark_chinese/astronomical-clocktower.png",
      civ: ["CHI"],
    },
    {
      title: "Imperial Palace",
      age: "2",
      imgSrc: "/assets/pictures/landmark_chinese/imperial-palace.png",
      civ: ["CHI"],
    },
    {
      title: "Great Wall Gatehouse",
      age: "3",
      imgSrc: "/assets/pictures/landmark_chinese/great-wall-gatehouse.png",
      civ: ["CHI"],
    },
    {
      title: "Spirit Way",
      age: "3",
      imgSrc: "/assets/pictures/landmark_chinese/spirit-way.png",
      civ: ["CHI"],
    },
    {
      title: "Dome of the Faith",
      age: "1",
      imgSrc: "/assets/pictures/landmark_delhi/dome-of-the-faith.png",
      civ: ["DEL"],
    },
    {
      title: "Tower of Victory",
      age: "1",
      imgSrc: "/assets/pictures/landmark_delhi/tower-of-victory.png",
      civ: ["DEL"],
    },
    {
      title: "Compound of the Defender",
      age: "2",
      imgSrc: "/assets/pictures/landmark_delhi/compound-of-the-defender.png",
      civ: ["DEL"],
    },
    {
      title: "House of Learning",
      age: "2",
      imgSrc: "/assets/pictures/landmark_delhi/house-of-learning.png",
      civ: ["DEL"],
    },
    {
      title: "Hisar Academy",
      age: "3",
      imgSrc: "/assets/pictures/landmark_delhi/hisar-academy.png",
      civ: ["DEL"],
    },
    {
      title: "Palace of the Sultan",
      age: "3",
      imgSrc: "/assets/pictures/landmark_delhi/palace-of-the-sultan.png",
      civ: ["DEL"],
    },
    {
      title: "Great Palace of Agra",
      age: "4",
      imgSrc: "/assets/pictures/landmark_delhi/great-palace-of-agra.png",
      civ: ["DEL"],
    },
    {
      title: "Enclave of the Emperor",
      age: "4",
      imgSrc: "/assets/pictures/landmark_chinese/enclave-of-the-emperor.png",
      civ: ["CHI"],
    },
    {
      title: "Great Mosque of Kairouan",
      age: "4",
      imgSrc: "/assets/pictures/landmark_abbasid/prayer-hall-of-uqba.png",
      civ: ["ABB"],
    },
  ];

  const tech_eco = [
    {
      title: "Double Broadax",
      age: "2",
      imgSrc: "/assets/pictures/technology_economy/double-broadaxe.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Lumber Preservation",
      age: "3",
      imgSrc: "/assets/pictures/technology_economy/lumber-preservation.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Crosscut Saw",
      age: "4",
      imgSrc: "/assets/pictures/technology_economy/crosscut-saw.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Forestry",
      age: "1",
      imgSrc: "/assets/pictures/technology_economy/forestry.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Horticulture",
      age: "2",
      imgSrc: "/assets/pictures/technology_economy/horticulture.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Fertilization",
      age: "3",
      imgSrc: "/assets/pictures/technology_economy/fertilization.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Precision Cross-Breeding",
      age: "4",
      imgSrc:
        "/assets/pictures/technology_economy/precision-cross-breeding.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Wheelbarrow",
      age: "1",
      imgSrc: "/assets/pictures/technology_economy/wheelbarrow.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Specialized Pick",
      age: "2",
      imgSrc: "/assets/pictures/technology_economy/specialized-pick.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Acid Distillation",
      age: "3",
      imgSrc: "/assets/pictures/technology_economy/acid-distilization.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Cupellation",
      age: "4",
      imgSrc: "/assets/pictures/technology_economy/cupellation.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Textiles",
      age: "2",
      imgSrc: "/assets/pictures/technology_economy/textiles.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Survival Techniques",
      age: "1",
      imgSrc: "/assets/pictures/technology_economy/survival-techniques.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Professional Scouts",
      age: "2",
      imgSrc: "/assets/pictures/technology_economy/professional-scouts.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Extended Lines",
      age: "2",
      imgSrc: "/assets/pictures/technology_economy/extended-lines.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Drift Nets",
      age: "3",
      imgSrc: "/assets/pictures/technology_economy/drift-nets.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Improved Processing",
      age: "1",
      imgSrc: "/assets/pictures/technology_abbasid/improved-processing.png",
      civ: ["ABB"],
    },
    {
      title: "Agriculture",
      age: "3",
      imgSrc: "/assets/pictures/technology_abbasid/agriculture.png",
      civ: ["ABB"],
    },
    {
      title: "Preservation of Knowledge",
      age: "2",
      imgSrc:
        "/assets/pictures/technology_abbasid/preservation-of-knowledge.png",
      civ: ["ABB"],
    },
    {
      title: "Armored Caravans",
      age: "3",
      imgSrc: "/assets/pictures/technology_abbasid/armored-caravans.png",
      civ: ["ABB"],
    },
    {
      title: "Grand Bazaar",
      age: "2",
      imgSrc: "/assets/pictures/technology_abbasid/grand-bazaar.png",
      civ: ["ABB"],
    },
    {
      title: "Spice Roads",
      age: "4",
      imgSrc: "/assets/pictures/technology_abbasid/spice-roads.png",
      civ: ["ABB"],
    },
    {
      title: "Fresh Foodstuffs",
      age: "2",
      imgSrc: "/assets/pictures/technology_abbasid/fresh-foodstuffs.png",
      civ: ["ABB"],
    },
    {
      title: "Fertile Crescent",
      age: "2",
      imgSrc: "/assets/pictures/technology_abbasid/fertile-crescent-2.png",
      civ: ["ABB"],
    },
    {
      title: "Extra Materials",
      age: "3",
      imgSrc: "/assets/pictures/technology_chinese/extra-materials.png",
      civ: ["CHI"],
    },
    {
      title: "Ancient Techniques",
      age: "4",
      imgSrc: "/assets/pictures/technology_chinese/ancient-techniques.png",
      civ: ["CHI"],
    },
    {
      title: "Imperial Examinations",
      age: "2",
      imgSrc: "/assets/pictures/technology_chinese/imperial-examination.png",
      civ: ["CHI"],
    },
    {
      title: "Village Fortresses",
      age: "3",
      imgSrc: "/assets/pictures/technology_delhi/village-fortresses.png",
      civ: ["DEL"],
    },
    {
      title: "Reinforced Foundations",
      age: "3",
      imgSrc: "/assets/pictures/technology_delhi/reinforced-foundations.png",
      civ: ["DEL"],
    },
    {
      title: "All-Seeing Eye",
      age: "2",
      imgSrc: "/assets/pictures/technology_delhi/all-seeing-eye.png",
      civ: ["DEL"],
    },
    {
      title: "Sanctity",
      age: "2",
      imgSrc: "/assets/pictures/technology_delhi/sanctity.png",
      civ: ["DEL"],
    },
    {
      title: "Swiftness",
      age: "3",
      imgSrc: "/assets/pictures/technology_delhi/swiftness.png",
      civ: ["DEL"],
    },
    {
      title: "Hearty Rations",
      age: "3",
      imgSrc: "/assets/pictures/technology_delhi/hearty-rations.png",
      civ: ["DEL"],
    },
    {
      title: "Enclosures",
      age: "4",
      imgSrc: "/assets/pictures/technology_english/enclosures.png",
      civ: ["ENG"],
    },
    {
      title: "Enlistment Incentives",
      age: "4",
      imgSrc: "/assets/pictures/technology_french/enlistment-incentives.png",
      civ: ["FRE"],
    },
    {
      title: "Benediction",
      age: "3",
      imgSrc: "/assets/pictures/technology_hre/benediction.png",
      civ: ["HRE"],
    },
    {
      title: "Devoutness",
      age: "3",
      imgSrc: "/assets/pictures/technology_hre/devoutness.png",
      civ: ["HRE"],
    },
    {
      title: "Piracy",
      age: "2",
      imgSrc: "/assets/pictures/technology_mongols/piracy.png",
      civ: ["MON"],
    },
    {
      title: "Superior Mobility",
      age: "1",
      imgSrc: "/assets/pictures/technology_mongols/superior-mobility.png",
      civ: ["MON"],
    },
    {
      title: "Raid Bounty",
      age: "2",
      imgSrc: "/assets/pictures/technology_mongols/raid-bounty.png",
      civ: ["MON"],
    },
    {
      title: "Stone Bounty",
      age: "4",
      imgSrc: "/assets/pictures/technology_mongols/stone-bounty.png",
      civ: ["MON"],
    },
    {
      title: "Stone Commerce",
      age: "4",
      imgSrc: "/assets/pictures/technology_mongols/stone-commerce.png",
      civ: ["MON"],
    },
    {
      title: "Anatolian Hills",
      age: "1",
      imgSrc: "/assets/pictures/technology_ottomans/anatolian-hills-1.png",
      civ: ["OTT"],
    },
    {
      title: "Trade Bags",
      age: "1",
      imgSrc: "/assets/pictures/technology_ottomans/trade-bags-1.png",
      civ: ["OTT"],
    },
  ];

  const tech_military = [
    {
      title: "Bloomery",
      age: "2",
      imgSrc: "/assets/pictures/technology_military/bloomery.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Decarbonization",
      age: "3",
      imgSrc: "/assets/pictures/technology_military/decarbonization.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Damascus Steel",
      age: "4",
      imgSrc: "/assets/pictures/technology_military/damascus-steel.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Siege Engineering",
      age: "2",
      imgSrc: "/assets/pictures/technology_military/siege-engineering.png",
      civ: [
        "ENG",
        "RUS",
        "MAL",
        "FRE",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Steeled Arrow",
      age: "2",
      imgSrc: "/assets/pictures/technology_military/steeled-arrow.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Balanced Projectiles",
      age: "3",
      imgSrc: "/assets/pictures/technology_military/balanced-projectiles.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Platecutter Point",
      age: "4",
      imgSrc: "/assets/pictures/technology_military/platecutter-point.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Military Academy",
      age: "4",
      imgSrc: "/assets/pictures/technology_military/military-academy.png",
      civ: ["ENG", "RUS", "MAL", "FRE", "MON", "ABB", "CHI", "DEL", "HRE"],
    },
    {
      title: "Fitted Leatherwork",
      age: "2",
      imgSrc: "/assets/pictures/technology_military/fitted-leatherwork.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Insulated Helm",
      age: "3",
      imgSrc: "/assets/pictures/technology_military/insulated-helm.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Master Smiths",
      age: "4",
      imgSrc: "/assets/pictures/technology_military/master-smiths.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Elite Army Tactics",
      age: "4",
      imgSrc: "/assets/pictures/technology_military/elite-army-tactics.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Iron Undermesh",
      age: "2",
      imgSrc: "/assets/pictures/technology_military/iron-undermesh.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Wedge Rivets",
      age: "3",
      imgSrc: "/assets/pictures/technology_military/wedge-rivets.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Angled Surfaces",
      age: "4",
      imgSrc: "/assets/pictures/technology_military/angled-surfaces.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Incendiary Arrows",
      age: "4",
      imgSrc: "/assets/pictures/technology_military/incendiary-arrows.png",
      civ: ["ENG", "FRE", "RUS", "MON", "ABB", "OTT", "CHI", "DEL", "HRE"],
    },
    {
      title: "Biology",
      age: "4",
      imgSrc: "/assets/pictures/technology_military/biology.png",
      civ: ["ENG", "RUS", "MAL", "MON", "ABB", "OTT", "CHI", "DEL", "HRE"],
    },
    {
      title: "Chemistry",
      age: "4",
      imgSrc: "/assets/pictures/technology_military/chemistry.png",
      civ: [
        "ENG",
        "RUS",
        "MAL",
        "FRE",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Geometry",
      age: "4",
      imgSrc: "/assets/pictures/technology_military/geometry.png",
      civ: [
        "ENG",
        "RUS",
        "MAL",
        "FRE",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Greased Axles",
      age: "2",
      imgSrc: "/assets/pictures/technology_military/greased-axles.png",
      civ: [
        "ENG",
        "RUS",
        "MAL",
        "FRE",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Roller Shutter Triggers",
      age: "4",
      imgSrc: "/assets/pictures/technology_units/roller-shutter-triggers.png",
      civ: [
        "ENG",
        "RUS",
        "MAL",
        "FRE",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Adjustable Crossbars",
      age: "4",
      imgSrc: "/assets/pictures/technology_units/adjustable-crossbars.png",
      civ: ["ENG", "RUS", "MAL", "FRE", "MON", "ABB", "OTT", "DEL", "HRE"],
    },
    {
      title: "Siege Works",
      age: "4",
      imgSrc: "/assets/pictures/technology_military/siege-works.png",
      civ: [
        "ENG",
        "RUS",
        "MAL",
        "FRE",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Arrowslits",
      age: "2",
      imgSrc: "/assets/pictures/technology_defensive/arrow-slits.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Springald Emplacement",
      age: "3",
      imgSrc: "/assets/pictures/technology_defensive/springald-emplacement.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Cannon Emplacement",
      age: "3",
      imgSrc: "/assets/pictures/technology_defensive/cannon-emplacement.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Boiling Oil",
      age: "3",
      imgSrc: "/assets/pictures/technology_defensive/boiling-oil.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Court Architects",
      age: "4",
      imgSrc: "/assets/pictures/technology_defensive/court-architects.png",
      civ: ["ENG", "FRE", "RUS", "MAL", "ABB", "OTT", "CHI", "DEL", "HRE"],
    },
    {
      title: "Fortify Outpost",
      age: "2",
      imgSrc: "/assets/pictures/technology_defensive/fortify-outpost.png",
      civ: ["ENG", "FRE", "MAL", "ABB", "OTT", "CHI", "DEL", "HRE"],
    },
    {
      title: "Extra Hammocks",
      age: "31",
      imgSrc: "/assets/pictures/technology_chinese/extra-hammocks.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Naval Arrowslits",
      age: "2",
      imgSrc: "/assets/pictures/technology_defensive/arrow-slits.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Composite Bows",
      age: "3",
      imgSrc: "/assets/pictures/technology_abbasid/composite-bows.png",
      civ: ["ABB"],
    },
    {
      title: "Camel Rider Barding",
      age: "4",
      imgSrc: "/assets/pictures/technology_abbasid/camel-rider-barding-4.png",
      civ: ["ABB"],
    },
    {
      title: "Camel Handling",
      age: "3",
      imgSrc: "/assets/pictures/technology_abbasid/camel-handling.png",
      civ: ["ABB"],
    },
    {
      title: "Camel Support",
      age: "4",
      imgSrc: "/assets/pictures/technology_abbasid/camel-support.png",
      civ: ["ABB"],
    },
    {
      title: "Camel Rider Shields",
      age: "3",
      imgSrc: "/assets/pictures/technology_abbasid/camel-rider-shields.png",
      civ: ["ABB"],
    },
    {
      title: "Medical Centers",
      age: "3",
      imgSrc: "/assets/pictures/technology_abbasid/medical-centers.png",
      civ: ["ABB"],
    },
    {
      title: "Boot Camp",
      age: "2",
      imgSrc: "/assets/pictures/technology_abbasid/boot-camp.png",
      civ: ["ABB"],
    },
    {
      title: "Teak Masts",
      age: "3",
      imgSrc: "/assets/pictures/technology_abbasid/teak-masts.png",
      civ: ["ABB"],
    },
    {
      title: "Proselytization",
      age: "4",
      imgSrc: "/assets/pictures/technology_abbasid/faith.png",
      civ: ["ABB"],
    },
    {
      title: "Phalanx",
      age: "2",
      imgSrc: "/assets/pictures/technology_abbasid/phalanx.png",
      civ: ["ABB"],
    },
    {
      title: "Pyrotechnics",
      age: "4",
      imgSrc: "/assets/pictures/technology_chinese/pyrotechnics.png",
      civ: ["CHI"],
    },
    {
      title: "Reload Drills",
      age: "4",
      imgSrc: "/assets/pictures/technology_chinese/reload-drills.png",
      civ: ["CHI"],
    },
    {
      title: "Reusable Barrels",
      age: "4",
      imgSrc: "/assets/pictures/technology_chinese/reusable-barrels.png",
      civ: ["CHI"],
    },
    {
      title: "Battle Hardened",
      age: "4",
      imgSrc: "/assets/pictures/technology_chinese/battle-hardened.png",
      civ: ["CHI"],
    },
    {
      title: "Handcannon Slits",
      age: "2",
      imgSrc: "/assets/pictures/technology_chinese/handcannon-slits.png",
      civ: ["CHI"],
    },
    {
      title: "Thunderclap Bombs",
      age: "4",
      imgSrc: "/assets/pictures/technology_chinese/thunderclap-bombs-4.png",
      civ: ["CHI"],
    },
    {
      title: "Armored Beasts",
      age: "4",
      imgSrc: "/assets/pictures/technology_delhi/armored-beasts.png",
      civ: ["DEL"],
    },
    {
      title: "Efficient Production",
      age: "1",
      imgSrc: "/assets/pictures/technology_delhi/efficient-production.png",
      civ: ["DEL"],
    },
    {
      title: "Howdahs",
      age: "4",
      imgSrc: "/assets/pictures/technology_delhi/siege-elephant.png",
      civ: ["DEL"],
    },
    {
      title: "Forced March",
      age: "3",
      imgSrc: "/assets/pictures/technology_delhi/forced-march.png",
      civ: ["DEL"],
    },
    {
      title: "Zeal",
      age: "4",
      imgSrc: "/assets/pictures/technology_delhi/zeal.png",
      civ: ["DEL"],
    },
    {
      title: "Honed Blades",
      age: "3",
      imgSrc: "/assets/pictures/technology_delhi/honed-blades.png",
      civ: ["DEL"],
    },
    {
      title: "Tranquil Venue",
      age: "3",
      imgSrc: "/assets/pictures/technology_delhi/tranquil-venue.png",
      civ: ["DEL"],
    },
    {
      title: "Lookout Towers",
      age: "3",
      imgSrc: "/assets/pictures/technology_delhi/lookout-towers.png",
      civ: ["DEL"],
    },
    {
      title: "Slow-Burning Defenses",
      age: "4",
      imgSrc: "/assets/pictures/technology_delhi/slow-burning-defenses.png",
      civ: ["DEL"],
    },
    {
      title: "Manuscript Trade",
      age: "1",
      imgSrc: "/assets/pictures/technology_delhi/manuscript-trade-1.png",
      civ: ["DEL"],
    },
    {
      title: "Crossbow Stirrups",
      age: "4",
      imgSrc: "/assets/pictures/technology_french/crossbow-stirrups.png",
      civ: ["FRE"],
    },
    {
      title: "Gambesons",
      age: "3",
      imgSrc: "/assets/pictures/technology_french/gambesons.png",
      civ: ["FRE"],
    },
    {
      title: "Chivalry ",
      age: "2",
      imgSrc: "/assets/pictures/technology_french/chivalry.png",
      civ: ["FRE"],
    },
    {
      title: "Royal Bloodlines",
      age: "4",
      imgSrc: "/assets/pictures/technology_french/royal-bloodlines.png",
      civ: ["FRE"],
    },
    {
      title: "Cantled Saddles",
      age: "3",
      imgSrc: "/assets/pictures/technology_french/cantled-saddles.png",
      civ: ["FRE"],
    },
    {
      title: "Long Guns",
      age: "3",
      imgSrc: "/assets/pictures/technology_french/long-guns.png",
      civ: ["FRE"],
    },
    {
      title: "Slate and Stone Construction",
      age: "3",
      imgSrc:
        "/assets/pictures/technology_hre/slate-and-stone-construction.png",
      civ: ["HRE"],
    },
    {
      title: "Reinforced Defenses",
      age: "4",
      imgSrc: "/assets/pictures/technology_hre/reinforced-defenses.png",
      civ: ["HRE"],
    },
    {
      title: "Marching Drills",
      age: "2",
      imgSrc: "/assets/pictures/technology_hre/marching-drills.png",
      civ: ["HRE"],
    },
    {
      title: "Heavy Maces",
      age: "3",
      imgSrc: "/assets/pictures/technology_hre/heavy-maces.png",
      civ: ["HRE"],
    },
    {
      title: "Two-Handed Weapons",
      age: "3",
      imgSrc: "/assets/pictures/technology_hre/two-handed-weapon.png",
      civ: ["HRE"],
    },
    {
      title: "Fire Stations",
      age: "2",
      imgSrc: "/assets/pictures/technology_hre/fire-stations.png",
      civ: ["HRE"],
    },
    {
      title: "Inspired Warriors",
      age: "3",
      imgSrc: "/assets/pictures/technology_hre/inspired-warriors.png",
      civ: ["HRE"],
    },
    {
      title: "Riveted Chain Mail",
      age: "4",
      imgSrc: "/assets/pictures/technology_hre/riveted-chain-mail-2.png",
      civ: ["HRE"],
    },
    {
      title: "Steel Barding",
      age: "4",
      imgSrc: "/assets/pictures/technology_hre/steel-barding-3.png",
      civ: ["HRE"],
    },
    {
      title: "Network of Citadels",
      age: "3",
      imgSrc: "/assets/pictures/technology_english/network-of-citadels.png",
      civ: ["ENG"],
    },
    {
      title: "Arrow Volley",
      age: "4",
      imgSrc: "/assets/pictures/technology_english/arrow-volley.png",
      civ: ["ENG"],
    },
    {
      title: "Setup Camp",
      age: "2",
      imgSrc: "/assets/pictures/technology_english/setup-camp.png",
      civ: ["ENG"],
    },
    {
      title: "Armor Clad",
      age: "3",
      imgSrc: "/assets/pictures/technology_english/armor-clad.png",
      civ: ["ENG"],
    },
    {
      title: "Admiralty",
      age: "2",
      imgSrc: "/assets/pictures/technology_english/admiralty-2.png",
      civ: ["ENG"],
    },
    {
      title: "Shattering Projectiles",
      age: "4",
      imgSrc: "/assets/pictures/technology_english/shattering-projectiles.png",
      civ: ["ENG"],
    },
    {
      title: "Banco Repairs",
      age: "2",
      imgSrc: "/assets/pictures/technology_malians/banco-repairs-2.png",
      civ: ["MAL"],
    },
    {
      title: "Farima Leadership",
      age: "4",
      imgSrc: "/assets/pictures/technology_malians/farima-leadership-4.png",
      civ: ["MAL"],
    },
    {
      title: "Imported Armor",
      age: "3",
      imgSrc: "/assets/pictures/technology_malians/imported-armor-3.png",
      civ: ["MAL"],
    },
    {
      title: "Local Knowledge",
      age: "3",
      imgSrc: "/assets/pictures/technology_malians/local-knowledge-4.png",
      civ: ["MAL"],
    },
    {
      title: "Poisoned Arrows",
      age: "3",
      imgSrc: "/assets/pictures/technology_malians/poisoned-arrows-3.png",
      civ: ["MAL"],
    },
    {
      title: "Precision Training",
      age: "3",
      imgSrc: "/assets/pictures/technology_malians/precision-training-4.png",
      civ: ["MAL"],
    },
    {
      title: "Canoe Tactics",
      age: "2",
      imgSrc: "/assets/pictures/technology_malians/canoe-tactics-2.png",
      civ: ["MAL"],
    },
    {
      title: "Whistling Arrows",
      age: "2",
      imgSrc: "/assets/pictures/technology_mongols/whistling-arrows.png",
      civ: ["MON"],
    },
    {
      title: "Yam Network",
      age: "3",
      imgSrc: "/assets/pictures/technology_mongols/yam-network.png",
      civ: ["MON"],
    },
    {
      title: "Additional Torches",
      age: "3",
      imgSrc: "/assets/pictures/technology_mongols/additional-torches.png",
      civ: ["MON"],
    },
    {
      title: "Monastic Shrines",
      age: "4",
      imgSrc: "/assets/pictures/technology_mongols/monastic-shrines.png",
      civ: ["MON"],
    },
    {
      title: "Siha Bow Limbs",
      age: "3",
      imgSrc: "/assets/pictures/technology_mongols/siha-bow-limbs.png",
      civ: ["MON"],
    },
    {
      title: "Armored Hull",
      age: "3",
      imgSrc: "/assets/pictures/technology_naval/armored-hull.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Shipwrights",
      age: "3",
      imgSrc: "/assets/pictures/technology_naval/shipwrights-4.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Herbal Medicine",
      age: "3",
      imgSrc: "/assets/pictures/technology_religious/herbal-medicine.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Piety",
      age: "4",
      imgSrc: "/assets/pictures/technology_religious/piety.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Tithe Barns",
      age: "4",
      imgSrc: "/assets/pictures/technology_religious/tithe-barns.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Janissary Guns",
      age: "4",
      imgSrc: "/assets/pictures/technology_ottomans/janissary-guns-4.png",
      civ: ["OTT"],
    },
    {
      title: "Imperial Fleet",
      age: "4",
      imgSrc: "/assets/pictures/technology_ottomans/imperial-fleet-4.png",
      civ: ["OTT"],
    },
    {
      title: "Advanced Academy",
      age: "1",
      imgSrc: "/assets/pictures/technology_ottomans/advanced-academy-1.png",
      civ: ["OTT"],
    },
    {
      title: "Fast Training",
      age: "1",
      imgSrc: "/assets/pictures/technology_ottomans/fast-training-1.png",
      civ: ["OTT"],
    },
    {
      title: "Field Work",
      age: "1",
      imgSrc: "/assets/pictures/technology_ottomans/field-work-1.png",
      civ: ["OTT"],
    },
    {
      title: "Janissary Company",
      age: "1",
      imgSrc: "/assets/pictures/technology_ottomans/janissary-company-1.png",
      civ: ["OTT"],
    },
    {
      title: "Mehter Drums",
      age: "1",
      imgSrc: "/assets/pictures/technology_ottomans/mehter-drums-1.png",
      civ: ["OTT"],
    },
    {
      title: "Military Campus",
      age: "1",
      imgSrc: "/assets/pictures/technology_ottomans/military-campus-1.png",
      civ: ["OTT"],
    },
    {
      title: "Siege Crews",
      age: "1",
      imgSrc: "/assets/pictures/technology_ottomans/siege-crews-1.png",
      civ: ["OTT"],
    },
    {
      title: "Fine Tuned Guns",
      age: "4",
      imgSrc: "/assets/pictures/technology_rus/fine-tuned-guns.png",
      civ: ["RUS"],
    },
    {
      title: "Boyar's Fortitude",
      age: "3",
      imgSrc: "/assets/pictures/technology_rus/boyars-fortitude.png",
      civ: ["RUS"],
    },
    {
      title: "Mounted Precision",
      age: "4",
      imgSrc: "/assets/pictures/technology_rus/mounted-precision.png",
      civ: ["RUS"],
    },
    {
      title: "Knight Sabers",
      age: "4",
      imgSrc: "/assets/pictures/technology_rus/knight-sabers.png",
      civ: ["RUS"],
    },
    {
      title: "Siege Crew Training",
      age: "4",
      imgSrc: "/assets/pictures/technology_rus/siege-crew-training.png",
      civ: ["RUS"],
    },
    {
      title: "Wandering Town",
      age: "4",
      imgSrc: "/assets/pictures/technology_rus/wandering-town.png",
      civ: ["RUS"],
    },
    {
      title: "Divine Light",
      age: "3",
      imgSrc: "/assets/pictures/technology_rus/blessing-duration.png",
      civ: ["RUS"],
    },
    {
      title: "Fervor",
      age: "3",
      imgSrc: "/assets/pictures/technology_rus/improved-blessing.png",
      civ: ["RUS"],
    },
    {
      title: "Saint's Veneration",
      age: "4",
      imgSrc: "/assets/pictures/technology_rus/saints-veneration-4.png",
      civ: ["RUS"],
    },
    {
      title: "Banded Arms",
      age: "4",
      imgSrc: "/assets/pictures/technology_rus/banded-arms.png",
      civ: ["RUS"],
    },
    {
      title: "Double Time",
      age: "4",
      imgSrc: "/assets/pictures/technology_rus/double-time.png",
      civ: ["RUS"],
    },
    {
      title: "Castle Watch",
      age: "2",
      imgSrc: "/assets/pictures/technology_rus/castle-watch.png",
      civ: ["RUS"],
    },
    {
      title: "Castle Turret",
      age: "2",
      imgSrc: "/assets/pictures/technology_rus/castle-turret.png",
      civ: ["RUS"],
    },
    {
      title: "Adaptable Hulls",
      age: "2",
      imgSrc: "/assets/pictures/technology_rus/adaptable-hulls-3.png",
      civ: ["RUS"],
    },
  ];

  const building_religious = [
    {
      title: "Monastery",
      age: "3",
      imgSrc: "/assets/pictures/building_religious/monastery.png",
      civ: ["ENG", "FRE", "RUS", "CHI", "HRE"],
    },
    {
      title: "Mosque",
      age: "3",
      imgSrc: "/assets/pictures/building_religious/mosque.png",
      civ: ["ABB", "DEL", "MAL", "OTT"],
    },
    {
      title: "Prayer Tent",
      age: "3",
      imgSrc: "/assets/pictures/building_mongols/prayer-tent.png",
      civ: ["MON"],
    },
    {
      title: "Pagoda",
      age: "3",
      imgSrc: "/assets/pictures/building_chinese/pagoda.png",
      civ: ["CHI"],
    },
  ];

  const building_eco = [
    {
      title: "Farm",
      age: "1",
      imgSrc: "/assets/pictures/building_economy/farm.png",
      civ: ["ENG", "FRE", "RUS", "MAL", "ABB", "OTT", "CHI", "DEL", "HRE"],
    },
    {
      title: "House",
      age: "1",
      imgSrc: "/assets/pictures/building_economy/house.png",
      civ: ["ENG", "FRE", "RUS", "MAL", "ABB", "OTT", "CHI", "DEL", "HRE"],
    },
    {
      title: "Lumber Camp",
      age: "1",
      imgSrc: "/assets/pictures/building_economy/lumber-camp.png",
      civ: ["ENG", "FRE", "RUS", "MAL", "ABB", "OTT", "CHI", "DEL", "HRE"],
    },
    {
      title: "Mining Camp",
      age: "1",
      imgSrc: "/assets/pictures/building_economy/mining-camp.png",
      civ: ["ENG", "FRE", "RUS", "MAL", "ABB", "OTT", "CHI", "DEL", "HRE"],
    },
    {
      title: "Mill",
      age: "1",
      imgSrc: "/assets/pictures/building_economy/mill.png",
      civ: ["ENG", "FRE", "MAL", "ABB", "OTT", "CHI", "DEL", "HRE"],
    },
    {
      title: "Pit Mine",
      age: "1",
      imgSrc: "/assets/pictures/building_malians/pit-mine-1.png",
      civ: ["MAL"],
    },
    {
      title: "Ger",
      age: "1",
      imgSrc: "/assets/pictures/building_mongols/ger.png",
      civ: ["MON"],
    },
    {
      title: "Pasture",
      age: "1",
      imgSrc: "/assets/pictures/building_mongols/pasture.png",
      civ: ["MON"],
    },
    {
      title: "Ovoo",
      age: "1",
      imgSrc: "/assets/pictures/building_mongols/ovoo.png",
      civ: ["MON"],
    },
    {
      title: "Hunting Cabin",
      age: "1",
      imgSrc: "/assets/pictures/building_rus/hunting-cabin.png",
      civ: ["RUS"],
    },
    {
      title: "Town Center (TC)",
      age: "2",
      imgSrc: "/assets/pictures/building_economy/town-center.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MON",
        "MAL",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Market",
      age: "2",
      imgSrc: "/assets/pictures/building_economy/market.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MON",
        "MAL",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Village",
      age: "2",
      imgSrc: "/assets/pictures/building_chinese/village.png",
      civ: ["CHI"],
    },
    {
      title: "Granary",
      age: "2",
      imgSrc: "/assets/pictures/building_chinese/granary.png",
      civ: ["CHI"],
    },
    {
      title: "Cattle Ranch",
      age: "2",
      imgSrc: "/assets/pictures/building_malians/cattle-ranch-2.png",
      civ: ["MAL"],
    },
  ];

  const building_tech = [
    {
      title: "Ovoo",
      age: "1",
      imgSrc: "/assets/pictures/building_mongols/ovoo.png",
      civ: ["MON"],
    },
    {
      title: "Blacksmith",
      age: "2",
      imgSrc: "/assets/pictures/building_technology/blacksmith.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "University",
      age: "2",
      imgSrc: "/assets/pictures/building_technology/university.png",
      civ: ["ENG", "FRE", "RUS", "OTT", "CHI", "HRE"],
    },
    {
      title: "Madrasa",
      age: "2",
      imgSrc: "/assets/pictures/building_technology/madrasa.png",
      civ: ["MAL", "ABB", "DEL"],
    },
  ];

  const building_military = [
    {
      title: "Barracks",
      age: "1",
      imgSrc: "/assets/pictures/building_military/barracks.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Military School",
      age: "1",
      imgSrc: "/assets/pictures/building_ottomans/military-school-1.png",
      civ: ["OTT"],
    },
    {
      title: "Archery Range",
      age: "2",
      imgSrc: "/assets/pictures/building_military/archery-range.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Stable",
      age: "2",
      imgSrc: "/assets/pictures/building_military/stable.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Siege Workshop",
      age: "3",
      imgSrc: "/assets/pictures/building_military/siege-workshop.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Dock",
      age: "1",
      imgSrc: "/assets/pictures/building_military/dock.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Keep",
      age: "3",
      imgSrc: "/assets/pictures/building_defensive/keep.png",
      civ: ["ENG", "FRE", "RUS", "MAL", "ABB", "OTT", "CHI", "DEL", "HRE"],
    },
    {
      title: "Outpost",
      age: "1",
      imgSrc: "/assets/pictures/building_defensive/outpost.png",
      civ: ["ENG", "FRE", "MON", "ABB", "OTT", "CHI", "DEL", "HRE"],
    },
    {
      title: "Toll Outpost",
      age: "1",
      imgSrc: "/assets/pictures/building_malians/toll-outpost-1.png",
      civ: ["MAL"],
    },
    {
      title: "Palisade Gate",
      age: "1",
      imgSrc: "/assets/pictures/building_defensive/palisade-gate.png",
      civ: ["ENG", "FRE", "MAL", "ABB", "OTT", "CHI", "DEL", "HRE"],
    },
    {
      title: "Palisade Wall",
      age: "1",
      imgSrc: "/assets/pictures/building_defensive/palisade-wall.png",
      civ: ["ENG", "FRE", "MAL", "ABB", "OTT", "CHI", "DEL", "HRE"],
    },
    {
      title: "Wooden Fortress",
      age: "1",
      imgSrc: "/assets/pictures/building_rus/wooden-fortress.png",
      civ: ["RUS"],
    },
    {
      title: "Fortified Palisade Gate",
      age: "1",
      imgSrc: "/assets/pictures/building_rus/fortified-palisade-gate.png",
      civ: ["RUS"],
    },
    {
      title: "Fortified Palisade Wall",
      age: "1",
      imgSrc: "/assets/pictures/building_rus/fortified-palisade-wall.png",
      civ: ["RUS"],
    },
    {
      title: "Stone Wall Gate",
      age: "3",
      imgSrc: "/assets/pictures/building_defensive/stone-wall-gate.png",
      civ: ["ENG", "FRE", "RUS", "MAL", "ABB", "OTT", "CHI", "DEL", "HRE"],
    },
    {
      title: "Stone Wall Tower",
      age: "3",
      imgSrc: "/assets/pictures/building_defensive/stone-wall-tower.png",
      civ: ["ENG", "FRE", "RUS", "MAL", "ABB", "OTT", "CHI", "DEL", "HRE"],
    },
  ];

  const unit_religious = [
    {
      title: "Monk",
      age: "3",
      imgSrc: "/assets/pictures/unit_religious/monk-3.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "OTT",
        "CHI",
        "HRE",
      ],
    },
    {
      title: "Imam",
      age: "3",
      imgSrc: "/assets/pictures/unit_abbasid/imam.png",
      civ: ["ABB"],
    },
    {
      title: "Scholar",
      age: "1",
      imgSrc: "/assets/pictures/unit_delhi/scholar.png",
      civ: ["DEL"],
    },
    {
      title: "Prelate",
      age: "1",
      imgSrc: "/assets/pictures/unit_hre/prelate.png",
      civ: ["HRE"],
    },
    {
      title: "Shaman",
      age: "1",
      imgSrc: "/assets/pictures/unit_mongols/shaman.png",
      civ: ["MON"],
    },
  ];

  const unit_military = [
    {
      title: "Scout",
      age: "1",
      imgSrc: "/assets/pictures/unit_cavalry/scout.png",
      civ: ["ENG", "FRE", "RUS", "MON", "ABB", "OTT", "CHI", "DEL", "HRE"],
    },
    {
      title: "Archer",
      age: "2",
      imgSrc: "/assets/pictures/unit_infantry/archer-2.png",
      civ: ["FRE", "RUS", "MAL", "MON", "ABB", "OTT", "CHI", "DEL", "HRE"],
    },
    {
      title: "Crossbowman",
      age: "3",
      imgSrc: "/assets/pictures/unit_infantry/crossbowman-3.png",
      civ: ["ENG", "RUS", "MON", "ABB", "OTT", "CHI", "DEL", "HRE"],
    },
    {
      title: "Handcannoneer",
      age: "4",
      imgSrc: "/assets/pictures/unit_infantry/handcannoneer-4.png",
      civ: ["ENG", "FRE", "MON", "ABB", "CHI", "DEL", "HRE"],
    },
    {
      title: "Spearman",
      age: "1",
      imgSrc: "/assets/pictures/unit_infantry/spearman-1.png",
      civ: ["ENG", "FRE", "RUS", "MON", "ABB", "OTT", "CHI", "DEL", "HRE"],
    },
    {
      title: "Man-at-Arms (MAA)",
      age: "3",
      imgSrc: "/assets/pictures/unit_infantry/man-at-arms-1.png",
      civ: ["ENG", "FRE", "RUS", "MON", "ABB", "OTT", "DEL", "HRE"],
    },
    {
      title: "Horseman",
      age: "2",
      imgSrc: "/assets/pictures/unit_cavalry/horseman-1.png",
      civ: ["ENG", "FRE", "RUS", "MON", "ABB", "OTT", "CHI", "DEL", "HRE"],
    },
    {
      title: "Knight",
      age: "3",
      imgSrc: "/assets/pictures/unit_cavalry/knight-2.png",
      civ: ["ENG", "RUS", "HRE"],
    },
    {
      title: "Lancer",
      age: "3",
      imgSrc: "/assets/pictures/unit_cavalry/lancer-3.png",
      civ: ["MON", "ABB", "OTT", "CHI", "DEL"],
    },
    {
      title: "Camel Rider",
      age: "3",
      imgSrc: "/assets/pictures/unit_abbasid/camel-rider-3.png",
      civ: ["ABB"],
    },
    {
      title: "Camel Archer",
      age: "2",
      imgSrc: "/assets/pictures/unit_abbasid/camel-archer-2.png",
      civ: ["ABB"],
    },
    {
      title: "Zhuge Nu",
      age: "2",
      imgSrc: "/assets/pictures/unit_chinese/zhuge-nu-2.png",
      civ: ["CHI"],
    },
    {
      title: "Palace Guard",
      age: "3",
      imgSrc: "/assets/pictures/unit_chinese/palace-guard-3.png",
      civ: ["CHI"],
    },
    {
      title: "Nest of Bees",
      age: "3",
      imgSrc: "/assets/pictures/unit_chinese/nest-of-bees.png",
      civ: ["CHI"],
    },
    {
      title: "Fire Lancer",
      age: "3",
      imgSrc: "/assets/pictures/unit_chinese/fire-lancer-3.png",
      civ: ["CHI"],
    },
    {
      title: "Grenadier",
      age: "4",
      imgSrc: "/assets/pictures/unit_chinese/grenadier-4.png",
      civ: ["CHI"],
    },
    {
      title: "Tower Elephant",
      age: "3",
      imgSrc: "/assets/pictures/unit_delhi/tower-elephant-3.png",
      civ: ["DEL"],
    },
    {
      title: "Sultan's Elite Tower Elephant",
      age: "4",
      imgSrc: "/assets/pictures/unit_delhi/sultans-elite-tower-elephant-4.png",
      civ: ["DEL"],
    },
    {
      title: "War Elephant",
      age: "3",
      imgSrc: "/assets/pictures/unit_delhi/war-elephant.png",
      civ: ["DEL"],
    },
    {
      title: "Longbowman",
      age: "2",
      imgSrc: "/assets/pictures/unit_english/longbowman-2.png",
      civ: ["ENG"],
    },
    {
      title: "King",
      age: "2",
      imgSrc: "/assets/pictures/unit_english/king-2.png",
      civ: ["ENG"],
    },
    {
      title: "Wynguard Ranger",
      age: "4",
      imgSrc: "/assets/pictures/unit_english/wynguard-ranger-4.png",
      civ: ["ENG"],
    },
    {
      title: "Wynguard Footmen",
      age: "4",
      imgSrc: "/assets/pictures/unit_english/wynguard-footmen-1.png",
      civ: ["ENG"],
    },
    {
      title: "Wynguard Army",
      age: "4",
      imgSrc: "/assets/pictures/unit_english/wynguard-army-1.png",
      civ: ["ENG"],
    },
    {
      title: "Wynguard Raiders",
      age: "4",
      imgSrc: "/assets/pictures/unit_english/wynguard-raiders-1.png",
      civ: ["ENG"],
    },
    {
      title: "Royal Knight",
      age: "2",
      imgSrc: "/assets/pictures/unit_french/royal-knight-2.png",
      civ: ["FRE"],
    },
    {
      title: "Arbalétrier",
      age: "3",
      imgSrc: "/assets/pictures/unit_french/arbaletrier-3.png",
      civ: ["FRE"],
    },
    {
      title: "Galleass",
      age: "3",
      imgSrc: "/assets/pictures/unit_french/galleass.png",
      civ: ["FRE"],
    },
    {
      title: "Cannon",
      age: "4",
      imgSrc: "/assets/pictures/unit_french/cannon-4.png",
      civ: ["FRE"],
    },
    {
      title: "Landsknecht",
      age: "4",
      imgSrc: "/assets/pictures/unit_hre/landsknecht-3.png",
      civ: ["HRE"],
    },
    {
      title: "Donso",
      age: "1",
      imgSrc: "/assets/pictures/unit_malians/donso-1.png",
      civ: ["MAL"],
    },
    {
      title: "Musofadi Warrior",
      age: "2",
      imgSrc: "/assets/pictures/unit_malians/musofadi-warrior-2.png",
      civ: ["MAL"],
    },
    {
      title: "Javelin Thrower",
      age: "2",
      imgSrc: "/assets/pictures/unit_malians/javelin-thrower-2.png",
      civ: ["MAL"],
    },
    {
      title: "Warrior Scout",
      age: "1",
      imgSrc: "/assets/pictures/unit_malians/warrior-scout-2.png",
      civ: ["MAL"],
    },
    {
      title: "Sofa",
      age: "2",
      imgSrc: "/assets/pictures/unit_malians/sofa-2.png",
      civ: ["MAL"],
    },
    {
      title: "Musofadi Gunner",
      age: "4",
      imgSrc: "/assets/pictures/unit_malians/musofadi-gunner-4.png",
      civ: ["MAL"],
    },
    {
      title: "Khan",
      age: "1",
      imgSrc: "/assets/pictures/unit_mongols/khan-1.png",
      civ: ["MON"],
    },
    {
      title: "Mangudai",
      age: "2",
      imgSrc: "/assets/pictures/unit_mongols/mangudai.png",
      civ: ["MON"],
    },
    {
      title: "Traction Trebuchet",
      age: "2",
      imgSrc: "/assets/pictures/unit_mongols/traction-trebuchet.png",
      civ: ["MON"],
    },
    {
      title: "Huihui Pao",
      age: "4",
      imgSrc: "/assets/pictures/unit_mongols/huihui-pao-1.png",
      civ: ["MON"],
    },
    {
      title: "Sipahi",
      age: "2",
      imgSrc: "/assets/pictures/unit_ottomans/sipahi-2.png",
      civ: ["OTT"],
    },
    {
      title: "Mehter",
      age: "2",
      imgSrc: "/assets/pictures/unit_ottomans/mehter-2.png",
      civ: ["OTT"],
    },
    {
      title: "Janissary",
      age: "3",
      imgSrc: "/assets/pictures/unit_ottomans/janissary-3.png",
      civ: ["OTT"],
    },
    {
      title: "Great Bombard",
      age: "4",
      imgSrc: "/assets/pictures/unit_ottomans/great-bombard-4.png",
      civ: ["OTT"],
    },
    {
      title: "Grand Galley",
      age: "4",
      imgSrc: "/assets/pictures/unit_ottomans/grand-galley-4.png",
      civ: ["OTT"],
    },
    {
      title: "Lodya Fishing Boat",
      age: "1",
      imgSrc: "/assets/pictures/unit_rus/lodya-fishing-boat.png",
      civ: ["RUS"],
    },
    {
      title: "Lodya Transport Ship",
      age: "1",
      imgSrc: "/assets/pictures/unit_rus/lodya-transport-ship.png",
      civ: ["RUS"],
    },
    {
      title: "Lodya Trade Ship",
      age: "2",
      imgSrc: "/assets/pictures/unit_rus/lodya-trade-ship.png",
      civ: ["RUS"],
    },
    {
      title: "Lodya Galley",
      age: "2",
      imgSrc: "/assets/pictures/unit_rus/lodya-galley-3.png",
      civ: ["RUS"],
    },
    {
      title: "Lodya Demolition Ship",
      age: "2",
      imgSrc: "/assets/pictures/unit_rus/lodya-demolition-ship.png",
      civ: ["RUS"],
    },
    {
      title: "Lodya Attack Ship",
      age: "2",
      imgSrc: "/assets/pictures/unit_rus/lodya-attack-ship.png",
      civ: ["RUS"],
    },
    {
      title: "Warrior Monk",
      age: "3",
      imgSrc: "/assets/pictures/unit_rus/warrior-monk.png",
      civ: ["RUS"],
    },
    {
      title: "Horse Archer",
      age: "3",
      imgSrc: "/assets/pictures/unit_rus/horse-archer-3.png",
      civ: ["RUS"],
    },
    {
      title: "Streltsy",
      age: "3",
      imgSrc: "/assets/pictures/unit_rus/streltsy.png",
      civ: ["RUS"],
    },
    {
      title: "Militia",
      age: "2",
      imgSrc: "/assets/pictures/unit_rus/militia-2.png",
      civ: ["RUS"],
    },
    {
      title: "Siege Tower",
      age: "2",
      imgSrc: "/assets/pictures/unit_siege/siege-tower.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Battering Ram",
      age: "2",
      imgSrc: "/assets/pictures/unit_siege/battering-ram.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Springald",
      age: "3",
      imgSrc: "/assets/pictures/unit_siege/springald.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Mangonel",
      age: "3",
      imgSrc: "/assets/pictures/unit_siege/mangonel-3.png",
      civ: ["ENG", "FRE", "RUS", "MAL", "MON", "ABB", "OTT", "DEL", "HRE"],
    },
    {
      title: "Counterweight Trebuchet",
      age: "3",
      imgSrc: "/assets/pictures/unit_siege/trebuchet.png",
      civ: ["ENG", "FRE", "RUS", "MAL", "CHI", "ABB", "OTT", "DEL", "HRE"],
    },
    {
      title: "Bombard",
      age: "3",
      imgSrc: "/assets/pictures/unit_siege/bombard.png",
      civ: ["ENG", "RUS", "MAL", "MON", "ABB", "CHI", "DEL", "HRE"],
    },
    {
      title: "Ribauldequin",
      age: "4",
      imgSrc: "/assets/pictures/unit_siege/ribauldequin-4.png",
      civ: ["ENG", "FRE", "OTT"],
    },
    {
      title: "Culverin",
      age: "4",
      imgSrc: "/assets/pictures/unit_siege/culverin-4.png",
      civ: ["ABB", "HRE", "FRE", "MAL"],
    },
    {
      title: "Dhow",
      age: "2",
      imgSrc: "/assets/pictures/unit_ship/dhow.png",
      civ: ["ABB", "DEL", "OTT"],
    },
    {
      title: "Galley",
      age: "2",
      imgSrc: "/assets/pictures/unit_ship/dhow.png",
      civ: ["ENG", "HRE", "FRE"],
    },
    {
      title: "Junk",
      age: "2",
      imgSrc: "/assets/pictures/unit_ship/dhow.png",
      civ: ["CHI"],
    },
    {
      title: "Light Junk",
      age: "2",
      imgSrc: "/assets/pictures/unit_ship/dhow.png",
      civ: ["MON"],
    },
    {
      title: "Hunting Canoe",
      age: "2",
      imgSrc: "/assets/pictures/unit_ship/dhow.png",
      civ: ["MAL"],
    },
    {
      title: "Baghlah",
      age: "2",
      imgSrc: "/assets/pictures/unit_ship/baghlah.png",
      civ: ["ABB", "DEL"],
    },
    {
      title: "Hulk",
      age: "2",
      imgSrc: "/assets/pictures/unit_ship/baghlah.png",
      civ: ["ENG", "FRE", "HRE", "OTT"],
    },
    {
      title: "War Junk",
      age: "2",
      imgSrc: "/assets/pictures/unit_ship/baghlah.png",
      civ: ["CHI", "MON"],
    },
    {
      title: "War Canoe",
      age: "2",
      imgSrc: "/assets/pictures/unit_ship/baghlah.png",
      civ: ["MAL"],
    },
    {
      title: "Explosive Dhow",
      age: "2",
      imgSrc: "/assets/pictures/unit_ship/explosive-dhow.png",
      civ: ["ABB", "DEL"],
    },
    {
      title: "Demolition Ship",
      age: "2",
      imgSrc: "/assets/pictures/unit_ship/explosive-dhow.png",
      civ: ["ENG", "FRE", "HRE", "MAL", "OTT"],
    },
    {
      title: "Explosive Junk",
      age: "2",
      imgSrc: "/assets/pictures/unit_ship/explosive-dhow.png",
      civ: ["CHI", "MON"],
    },
    {
      title: "Xebec",
      age: "4",
      imgSrc: "/assets/pictures/unit_ship/xebec.png",
      civ: ["ABB", "DEL"],
    },
    {
      title: "Carrack",
      age: "4",
      imgSrc: "/assets/pictures/unit_ship/xebec.png",
      civ: ["ENG", "FRE", "HRE", "OTT"],
    },
    {
      title: "Baochuan",
      age: "4",
      imgSrc: "/assets/pictures/unit_ship/xebec.png",
      civ: ["CHI", "MON"],
    },
  ];

  const unit_eco = [
    {
      title: "Villager",
      age: "1",
      imgSrc: "/assets/pictures/unit_worker/villager.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Scout",
      age: "1",
      imgSrc: "/assets/pictures/unit_cavalry/scout.png",
      civ: ["ENG", "FRE", "RUS", "MON", "ABB", "OTT", "CHI", "DEL", "HRE"],
    },
    {
      title: "Trader",
      age: "2",
      imgSrc: "/assets/pictures/unit_worker/trader.png",
      civ: [
        "ENG",
        "FRE",
        "RUS",
        "MAL",
        "MON",
        "ABB",
        "OTT",
        "CHI",
        "DEL",
        "HRE",
      ],
    },
    {
      title: "Imperial Official",
      age: "1",
      imgSrc: "/assets/pictures/unit_chinese/imperial-official.png",
      civ: ["CHI"],
    },
  ];

  return { getIcons };
}
