// Only the MDI icons the app actually uses, imported individually from
// @mdi/js so the bundler tree-shakes the rest (the full @mdi/font webfont was
// ~2.3 MB across formats). Regenerate after adding/removing icons with:
//   grep -rhoE "mdi-[a-z0-9-]+" src --include=*.vue --include=*.js | sort -u
import {
  mdiAccountCheck,
  mdiAccountEdit,
  mdiAccountOffOutline,
  mdiAccountOutline,
  mdiAccountStar,
  mdiAlertCircle,
  mdiAlertCircleOutline,
  mdiAlertDecagram,
  mdiApi,
  mdiArrowUpBold,
  mdiButtonCursor,
  mdiCalendar,
  mdiCamera,
  mdiChat,
  mdiCheck,
  mdiCheckCircle,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiCircleMedium,
  mdiClockEditOutline,
  mdiClose,
  mdiCloudUploadOutline,
  mdiCommentOutline,
  mdiContentCopy,
  mdiContentPaste,
  mdiContentSaveOutline,
  mdiDelete,
  mdiDotsVertical,
  mdiDownload,
  mdiDownloadMultiple,
  mdiEarth,
  mdiEmailOutline,
  mdiExportVariant,
  mdiEye,
  mdiEyeOffOutline,
  mdiEyeOutline,
  mdiFileDocumentOutline,
  mdiFilterVariant,
  mdiFlagVariant,
  mdiFormatListNumbered,
  mdiGithub,
  mdiHammer,
  mdiHeart,
  mdiHeartOutline,
  mdiHome,
  mdiIdentifier,
  mdiImageBrokenVariant,
  mdiImageMultiple,
  mdiImagePlus,
  mdiImageSearch,
  mdiInformation,
  mdiInformationOutline,
  mdiLockCheckOutline,
  mdiLockOutline,
  mdiLogin,
  mdiLogout,
  mdiMagnify,
  mdiMagnifyClose,
  mdiMap,
  mdiMenu,
  mdiMenuDown,
  mdiMessage,
  mdiMonitor,
  mdiPause,
  mdiPencil,
  mdiPencilCircle,
  mdiPlay,
  mdiPlaylistEdit,
  mdiPlus,
  mdiPublish,
  mdiRefresh,
  mdiSend,
  mdiShareVariant,
  mdiShieldAccount,
  mdiShieldOutline,
  mdiShuffleVariant,
  mdiSort,
  mdiStar,
  mdiStarOutline,
  mdiStrategy,
  mdiSwordCross,
  mdiSync,
  mdiTagOutline,
  mdiTextBoxOutline,
  mdiThumbDown,
  mdiThumbDownOutline,
  mdiThumbUp,
  mdiThumbUpOutline,
  mdiTrayArrowDown,
  mdiTrendingUp,
  mdiTrophy,
  mdiUndo,
  mdiVolumeMedium,
  mdiVolumeOff,
  mdiWeatherNight,
  mdiWhiteBalanceSunny,
  mdiYoutube,
} from "@mdi/js";

export const usedMdiIcons = {
  "mdi-account-check": mdiAccountCheck,
  "mdi-account-edit": mdiAccountEdit,
  "mdi-account-off-outline": mdiAccountOffOutline,
  "mdi-account-outline": mdiAccountOutline,
  "mdi-account-star": mdiAccountStar,
  "mdi-alert-circle": mdiAlertCircle,
  "mdi-alert-circle-outline": mdiAlertCircleOutline,
  "mdi-alert-decagram": mdiAlertDecagram,
  "mdi-api": mdiApi,
  "mdi-arrow-up-bold": mdiArrowUpBold,
  "mdi-button-cursor": mdiButtonCursor,
  "mdi-calendar": mdiCalendar,
  "mdi-camera": mdiCamera,
  "mdi-chat": mdiChat,
  "mdi-check": mdiCheck,
  "mdi-check-circle": mdiCheckCircle,
  "mdi-chevron-down": mdiChevronDown,
  "mdi-chevron-left": mdiChevronLeft,
  "mdi-chevron-right": mdiChevronRight,
  "mdi-chevron-up": mdiChevronUp,
  "mdi-circle-medium": mdiCircleMedium,
  "mdi-clock-edit-outline": mdiClockEditOutline,
  "mdi-close": mdiClose,
  "mdi-cloud-upload-outline": mdiCloudUploadOutline,
  "mdi-comment-outline": mdiCommentOutline,
  "mdi-content-copy": mdiContentCopy,
  "mdi-content-paste": mdiContentPaste,
  "mdi-content-save-outline": mdiContentSaveOutline,
  "mdi-delete": mdiDelete,
  "mdi-dots-vertical": mdiDotsVertical,
  "mdi-download": mdiDownload,
  "mdi-download-multiple": mdiDownloadMultiple,
  "mdi-earth": mdiEarth,
  "mdi-email-outline": mdiEmailOutline,
  "mdi-export-variant": mdiExportVariant,
  "mdi-eye": mdiEye,
  "mdi-eye-off-outline": mdiEyeOffOutline,
  "mdi-eye-outline": mdiEyeOutline,
  "mdi-file-document-outline": mdiFileDocumentOutline,
  "mdi-filter-variant": mdiFilterVariant,
  "mdi-flag-variant": mdiFlagVariant,
  "mdi-format-list-numbered": mdiFormatListNumbered,
  "mdi-github": mdiGithub,
  "mdi-hammer": mdiHammer,
  "mdi-heart": mdiHeart,
  "mdi-heart-outline": mdiHeartOutline,
  "mdi-home": mdiHome,
  "mdi-identifier": mdiIdentifier,
  "mdi-image-broken-variant": mdiImageBrokenVariant,
  "mdi-image-multiple": mdiImageMultiple,
  "mdi-image-plus": mdiImagePlus,
  "mdi-image-search": mdiImageSearch,
  "mdi-information": mdiInformation,
  "mdi-information-outline": mdiInformationOutline,
  "mdi-lock-check-outline": mdiLockCheckOutline,
  "mdi-lock-outline": mdiLockOutline,
  "mdi-login": mdiLogin,
  "mdi-logout": mdiLogout,
  "mdi-magnify": mdiMagnify,
  "mdi-magnify-close": mdiMagnifyClose,
  "mdi-map": mdiMap,
  "mdi-menu": mdiMenu,
  "mdi-menu-down": mdiMenuDown,
  "mdi-message": mdiMessage,
  "mdi-monitor": mdiMonitor,
  "mdi-pause": mdiPause,
  "mdi-pencil": mdiPencil,
  "mdi-pencil-circle": mdiPencilCircle,
  "mdi-play": mdiPlay,
  "mdi-playlist-edit": mdiPlaylistEdit,
  "mdi-plus": mdiPlus,
  "mdi-publish": mdiPublish,
  "mdi-refresh": mdiRefresh,
  "mdi-send": mdiSend,
  "mdi-share-variant": mdiShareVariant,
  "mdi-shield-account": mdiShieldAccount,
  "mdi-shield-outline": mdiShieldOutline,
  "mdi-shuffle-variant": mdiShuffleVariant,
  "mdi-sort": mdiSort,
  "mdi-star": mdiStar,
  "mdi-star-outline": mdiStarOutline,
  "mdi-strategy": mdiStrategy,
  "mdi-sword-cross": mdiSwordCross,
  "mdi-sync": mdiSync,
  "mdi-tag-outline": mdiTagOutline,
  "mdi-text-box-outline": mdiTextBoxOutline,
  "mdi-thumb-down": mdiThumbDown,
  "mdi-thumb-down-outline": mdiThumbDownOutline,
  "mdi-thumb-up": mdiThumbUp,
  "mdi-thumb-up-outline": mdiThumbUpOutline,
  "mdi-tray-arrow-down": mdiTrayArrowDown,
  "mdi-trending-up": mdiTrendingUp,
  "mdi-trophy": mdiTrophy,
  "mdi-undo": mdiUndo,
  "mdi-volume-medium": mdiVolumeMedium,
  "mdi-volume-off": mdiVolumeOff,
  "mdi-weather-night": mdiWeatherNight,
  "mdi-white-balance-sunny": mdiWhiteBalanceSunny,
  "mdi-youtube": mdiYoutube,
};
